x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: "3"

x-common: &common
  restart: always
  logging: *default-logging

services:
  jellyfin:
    <<: *common
    image: jellyfin/jellyfin:10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "${JELLYFIN_PORT:-8096}:8096"
    environment:
      - PUID=${PUID:-}
      - PGID=${PGID:-}
      - TZ=${TZ:-}
    volumes:
      - ${JELLYFIN_PATH_CONFIG:?JELLYFIN_PATH_CONFIG is required}:/config
      - ${JELLYFIN_PATH_CACHE:?JELLYFIN_PATH_CACHE is required}:/cache
      - ${JELLYFIN_PATH_PREVIEW:?JELLYFIN_PATH_PREVIEW is required}:/preview
      - ${JELLYFIN_PATH_VIDEO:?JELLYFIN_PATH_VIDEO is required}:/video
      - media_smb:/data/media
    networks:
      - media
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 4GB
        reservations:
          memory: 1GB

  audiobookshelf:
    <<: *common
    image: ghcr.io/advplyr/audiobookshelf:2.36.0@sha256:e388e90e381ae3fa8660346612b2955f2c555ede81c9c286e2218bdf966b4de8
    container_name: audiobookshelf
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Berlin}
    ports:
      - "${AUDIOBOOKSHELF_PORT:?AUDIOBOOKSHELF_PORT is required}:80"
    volumes:
      - ${AUDIOBOOKSHELF_PATH_CONFIG:?AUDIOBOOKSHELF_PATH_CONFIG is required}:/config
      - ${AUDIOBOOKSHELF_PATH_METADATA:?AUDIOBOOKSHELF_PATH_METADATA is required}:/metadata
      - audios_smb:/data/audios
    networks:
      - media
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
        reservations:
          memory: 256M

  jellyfin-exporter:
    <<: *common
    image: rebelcore/jellyfin-exporter:v1.5.1@sha256:8cce84da3ae704b03fd0d886cb583250913c77125cd4c7eef44ec4a28fa3d362
    container_name: jellyfin-exporter
    command:
      - --jellyfin.address=http://jellyfin:8096
      - --jellyfin.token=${JELLYFIN_API_KEY:?JELLYFIN_API_KEY is required}
    networks:
      - media
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 64M

networks:
  media:
    name: media-net
    external: true

volumes:
  media_smb:
    driver: local
    driver_opts:
      type: cifs
      device: "//${CIFS_MEDIA_HOST:?CIFS_MEDIA_HOST is required}/${CIFS_MEDIA_SHARE:?CIFS_MEDIA_SHARE is required}"
      o: "username=${CIFS_MEDIA_USER:?CIFS_MEDIA_USER is required},password=${CIFS_MEDIA_PASS:?CIFS_MEDIA_PASS is required},vers=3.0,uid=${PUID:-1000},gid=${PGID:-1000}"
  audios_smb:
    driver: local
    driver_opts:
      type: cifs
      device: "//${CIFS_AUDIO_HOST:?CIFS_AUDIO_HOST is required}/${CIFS_AUDIO_SHARE:?CIFS_AUDIO_SHARE is required}"
      o: "username=${CIFS_AUDIO_USER:?CIFS_AUDIO_USER is required},password=${CIFS_AUDIO_PASS:?CIFS_AUDIO_PASS is required},vers=3.0,uid=${PUID:-1000},gid=${PGID:-1000}"
