ansible_host: ENC[AES256_GCM,data:Je7IskT19MMs+0E=,iv:zRw2/QlhErhwqXfgHICjdyxuYKuejoE/cXcfln8hfi8=,tag:A2XxBUDUlysv/6IiLb3JLQ==,type:str]
ansible_user: ENC[AES256_GCM,data:hUAKM2M=,iv:3Gu6M0hSPqWRulFpReLjbsccPBqmvjyjxczi/uc+oLI=,tag:AUHzncW3U7mhRVIwgbNqLQ==,type:str]
hawser_dockhand_url: ENC[AES256_GCM,data:5f5BPIcNur8kQ4Hz6Aj5p40D8AR2uiKH5tb9faQyhVxOms7Mg72Y/A==,iv:U3PSiCFzv+ENXS7WAgBZrw/yATJ4KGd4/9QJ5YS4q5s=,tag:aFOp18iDydCR6C7VHjI5yg==,type:str]
hawser_dockhand_token: ENC[AES256_GCM,data:t638L7WqN5z0vAMief8GtWCZVZlxQOC17qBtTOMu4MqFpy7UamLWlLUDoQ==,iv:Hv77jZZvAVZJ5/DH3tLdZMOAoZ17YLr3jaFHNvBQmtE=,tag:T/pzqkFHPbvqsTOKII3dGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaWR0VlpWRU1rbTg4YTZa
            ZSttbjd6NW12T284Q25ZdGtqMnRZZkhBQjFZClpnS2VPMTVCYURmN293VW9uYWhY
            cXVRVkV2VTVqcVlnSkVIdi9kQUdtcmMKLS0tIDIxbXVSVE1tYzJHZEhNUGhsRDM2
            L25FaHltTjBVbVlTd2tRQW5CcXQ5clUKBICWJaYHluzqkq6SIE38svJlaLjsH6jL
            mnzjAUEy6DZHV+J4pY/M1QRrjC5u5we1zFKCzcqR8Tk6ZyQPQARGgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T05:23:17Z"
    mac: ENC[AES256_GCM,data:yYRUGtpmdrPpcz6oWfmCNGaAocwYrn80pCk2QRziRDAsNadVTd3NsAy+U/DHKUKNLp/vHIuqJbIJPaf6dslBa5MDOJwAIFwsQxxO90b4H5ebBO4GOleU5GBrIu4ahLWXr5Mb5lob5wYCyBBA2KNlgtOysKcOHh5Pqh8xw+S/09g=,iv:+RIyj7dps68PtY/qYwknzpFKTBRhkDaXxEpx2iVz6SA=,tag:desJBxOnwLhfdkZD3Mw5Hg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
