ansible_host: ENC[AES256_GCM,data:Je7IskT19MMs+0E=,iv:zRw2/QlhErhwqXfgHICjdyxuYKuejoE/cXcfln8hfi8=,tag:A2XxBUDUlysv/6IiLb3JLQ==,type:str]
ansible_user: ENC[AES256_GCM,data:hUAKM2M=,iv:3Gu6M0hSPqWRulFpReLjbsccPBqmvjyjxczi/uc+oLI=,tag:AUHzncW3U7mhRVIwgbNqLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaWR0VlpWRU1rbTg4YTZa
            ZSttbjd6NW12T284Q25ZdGtqMnRZZkhBQjFZClpnS2VPMTVCYURmN293VW9uYWhY
            cXVRVkV2VTVqcVlnSkVIdi9kQUdtcmMKLS0tIDIxbXVSVE1tYzJHZEhNUGhsRDM2
            L25FaHltTjBVbVlTd2tRQW5CcXQ5clUKBICWJaYHluzqkq6SIE38svJlaLjsH6jL
            mnzjAUEy6DZHV+J4pY/M1QRrjC5u5we1zFKCzcqR8Tk6ZyQPQARGgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-04T13:11:42Z"
    mac: ENC[AES256_GCM,data:z7OznPzzMdIS60EjKAksUv0WgYR2Is1Og25lmlyqd0z5nHBjnuXnckJ360aMrvOpkrBG/uzKJNPbInmQ1OKVCiwsWE+1hHLkLoUYCJFw1SAJJQEW6Cb9GSKOu8O0CtJHRLjnOaaEzlzWR21jSh6kvtoUbW3cJmL9uLzJEpQB3Eo=,iv:dZsgoyXJXJO4WTcilWv9IBzI5l1fZ/PK6npudo7wVxw=,tag:AnjmDK+spJ1UWP73K3Ecow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
