#ENC[AES256_GCM,data:sh+YHgjjYsnX/RMlzUQifU1ejLRnJlAALiUw+d4PA5ydqisTR+6ynykN,iv:iR2dNWWU0JUYDnd/ojSVCjboJNkE17ungBI2NTuJ5XY=,tag:7fU3AW/Ug2SX8KSAB/DGOg==,type:comment]
#ENC[AES256_GCM,data:mApBl/FxTGLn4JIYtT2gr2jUVN4wmP54oOlxw0k20JVeqhGPuMRCLtSfGYs/2A0+Ghdi98Zb,iv:s2N8Jz0AqYHFfF3P71m3+D/08lgZux/W3AQ7FOPW0+M=,tag:rJ5f+2bJ8jft4iN2CEkUnw==,type:comment]
ups_host: ENC[AES256_GCM,data:zSef9uv3+zU=,iv:F4pVfSmq+cOLjUD+X8TlLWvqyjSpGyqV+KxOb8yFld4=,tag:dee6U3XuGXJZm1WbDM9jgw==,type:str]
ups_password: ENC[AES256_GCM,data:3ZxRG4iqRTA=,iv:cVWMR1wVbbdjvspcgefflLYhgocgOZOdBwpcgMpOBfY=,tag:Xe0A0lmuIHuod4dB8GmjhA==,type:str]
agent_core_address: ENC[AES256_GCM,data:yrRGUC2ZLxobcfJqQ1omU6ll+hHz,iv:ns7FRDy5tPTeINSPfDUOVgCtt7qUB23gWwmTPUNBO6Y=,tag:6l22h4RVpz2wejMX0xVYbQ==,type:str]
agent_onboarding_key: ENC[AES256_GCM,data:tqHcsWSeQUlkFpCyyKkcsMb/YC5kk98n23i6lDGy2oI=,iv:FcZdwtkRnEKblmJG9309msTg8gqnbM1iYqMacT7zc2Y=,tag:CQ0e3eB79C0wAzpbQbB/Kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNXhCRTNSUE1mU1d5QUdF
            VU8yNllpcDQrUGhVdzhZREVWWGZMNmRnV2pRClRpK2g1SVZXWlpSV0wwVS9GaDJq
            TVlsbzFNUG9xK3A5bEJOZDhaSno3Q00KLS0tIC9odk9veUZ1cnphOHh0ZVZEMC80
            dWRtS04wNkxGK21wUlIwTVZlSnpiREUKgtExHKcaD4xoB1cuoZQ7q8M16rHUr65Z
            nSUBqC3IHbaF085xfhzgDJmw3XU+qQu2HWdmJD/VHrsekeDYWJMeXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T14:47:10Z"
    mac: ENC[AES256_GCM,data:4A0dVMnPMAWGRanrqy3hUMAZSe/9SGKYfOJDf8Uug626dsnXcUwl2ULuRUjKfiCnxRdaBhH78Jn6NEaHh7EN6FAkNXHAC+7VlM0eut+rWjSNeZQXUD4Qcm1rTIPk8WGfyxSnhevZOsoa8kaOfdqWXoxp8m+Fjr88KlXjbwwpL/o=,iv:aMfl5eQXaupLZiWBB7ZH561TGDtMekkdHyRzlTJbsyc=,tag:bKD/yoyHI+faAsFy1FQIJA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
