#!/bin/sh
set -e

# --- Source .env ---
ENV_FILE=""
for f in .env .env.stack compose.env; do
  [ -f "$f" ] && ENV_FILE="$f" && break
done

if [ -n "$ENV_FILE" ]; then
  echo "[pre-deploy] sourcing $ENV_FILE"
  while IFS= read -r line || [ -n "$line" ]; do
    line="$(printf '%s' "$line" | tr -d '\r')"
    case "$line" in \#*|'') continue ;; esac
    key="${line%%=*}"
    value="${line#*=}"
    export "$key=$value"
  done < "$ENV_FILE"
else
  echo "[pre-deploy] no .env file found, using shell environment"
fi

NZBGET_DIR="${NZBGET_PATH_CONFIG:-./nzbget/config}"
CONF="${NZBGET_DIR}/nzbget.conf"

echo "[pre-deploy] config dir: ${NZBGET_DIR}"

# --- Helper: update a key in-place, only if value differs ---
set_key() {
  key="$1"
  value="$2"
  if grep -q "^${key} *=" "$CONF"; then
    old="$(grep "^${key} *=" "$CONF" | head -1)"
    old_val="${old#*=}"
    old_val="$(printf '%s' "$old_val" | sed 's/^ *//')"
    if [ "$old_val" != "$value" ]; then
      sed -i "s|^${key} *=.*|${key}=${value}|" "$CONF"
      echo "[pre-deploy]   ${key}: ${old_val} -> ${value}"
    fi
  else
    printf '%s=%s\n' "$key" "$value" >> "$CONF"
    echo "[pre-deploy]   ${key}: <added> ${value}"
  fi
}

# --- Fresh generation ---
if [ ! -f "$CONF" ]; then
  mkdir -p "${NZBGET_DIR}"
  echo "[pre-deploy] generating nzbget.conf"

  cat > "$CONF" <<EOF
# Generated by pre-deploy.sh — NZBGet manages this file after first start

# --- Paths ---
MainDir=${NZBGET_MAIN_DIR:-/config}
DestDir=${NZBGET_DEST_DIR:-/data/completed}
InterDir=${NZBGET_INTER_DIR:-/data/intermediate}
TempDir=${NZBGET_TEMP_DIR:-/data/tmp}
NzbDir=${NZBGET_NZB_DIR:-/config/nzb}
QueueDir=${NZBGET_QUEUE_DIR:-/config/queue}

# --- Security ---
ControlIP=0.0.0.0
ControlPort=6789
ControlUsername=${NZBGET_USER:-nzbget}
ControlPassword=${NZBGET_PASS:-}
AuthorizedIP=
FormAuth=no
SecureControl=no

# --- News Server ---
Server1.Active=yes
Server1.Name=${NZBGET_SERVER1_NAME:-newsserver}
Server1.Host=${NZBGET_SERVER1_HOST}
Server1.Port=${NZBGET_SERVER1_PORT:-563}
Server1.Username=${NZBGET_SERVER1_USERNAME}
Server1.Password=${NZBGET_SERVER1_PASSWORD}
Server1.Encryption=yes
Server1.Connections=${NZBGET_SERVER1_CONNECTIONS:-20}
Server1.Retention=0
Server1.CertVerification=strict
Server1.IpVersion=auto

# --- Connection ---
ArticleTimeout=60
DownloadRate=${NZBGET_DOWNLOAD_RATE:-0}

# --- Logging ---
WriteLog=rotate
RotateLog=3
ErrorTarget=both
WarningTarget=both
InfoTarget=both
DetailTarget=log
DebugTarget=log
LogFile=\${MainDir}/nzbget.log

# --- Post-Processing ---
ParCheck=auto
ParRepair=yes
ParScan=extended
ParQuick=yes
PostStrategy=balanced
FileNaming=auto
ParBuffer=250
ParThreads=0
DirectUnpack=yes
Unpack=yes
DirectWrite=yes
ContinuePartial=yes
ArticleCache=250
EOF

  # Append categories
  ORDER=1
  IDX=1
  while true; do
    eval "CAT_NAME=\${NZBGET_CAT_${IDX}_NAME:-}"
    [ -z "$CAT_NAME" ] && break
    eval "CAT_DIR=\${NZBGET_CAT_${IDX}_DIR:-}"
    eval "CAT_UNPACK=\${NZBGET_CAT_${IDX}_UNPACK:-yes}"
    eval "CAT_ALIASES=\${NZBGET_CAT_${IDX}_ALIASES:-}"
    cat >> "$CONF" <<EOF

Category${ORDER}.Name=${CAT_NAME}
Category${ORDER}.DestDir=${CAT_DIR}
Category${ORDER}.Unpack=${CAT_UNPACK}
Category${ORDER}.Aliases=${CAT_ALIASES}
EOF
    ORDER=$((ORDER + 1))
    IDX=$((IDX + 1))
  done

  # Append tasks
  IDX=1
  while true; do
    eval "TASK_TIME=\${NZBGET_TASK_${IDX}_TIME:-}"
    [ -z "$TASK_TIME" ] && break
    eval "TASK_WEEKDAYS=\${NZBGET_TASK_${IDX}_WEEKDAYS:-1-7}"
    eval "TASK_COMMAND=\${NZBGET_TASK_${IDX}_COMMAND:-PauseDownload}"
    eval "TASK_PARAM=\${NZBGET_TASK_${IDX}_PARAM:-}"
    cat >> "$CONF" <<EOF

Task${IDX}.Time=${TASK_TIME}
Task${IDX}.WeekDays=${TASK_WEEKDAYS}
Task${IDX}.Command=${TASK_COMMAND}
Task${IDX}.Param=${TASK_PARAM}
EOF
    IDX=$((IDX + 1))
  done

  chown -R "${PUID:-1000}:${PGID:-1000}" "${NZBGET_DIR}" 2>/dev/null || true
  echo "[pre-deploy] nzbget.conf created"
  exit 0
fi

# --- Update existing config: only sync env-driven keys ---
echo "[pre-deploy] updating existing nzbget.conf"
CHANGES=0
count_before="$(cat "$CONF" | wc -l)"

# Paths
set_key "MainDir"    "${NZBGET_MAIN_DIR:-/config}"
set_key "DestDir"    "${NZBGET_DEST_DIR:-/data/completed}"
set_key "InterDir"   "${NZBGET_INTER_DIR:-/data/intermediate}"
set_key "TempDir"    "${NZBGET_TEMP_DIR:-/data/tmp}"
set_key "NzbDir"     "${NZBGET_NZB_DIR:-/config/nzb}"
set_key "QueueDir"   "${NZBGET_QUEUE_DIR:-/config/queue}"

# Auth
set_key "ControlUsername" "${NZBGET_USER:-nzbget}"
[ -n "${NZBGET_PASS}" ] && set_key "ControlPassword" "${NZBGET_PASS}"

# Server
[ -n "${NZBGET_SERVER1_HOST}" ]     && set_key "Server1.Host"        "${NZBGET_SERVER1_HOST}"
[ -n "${NZBGET_SERVER1_USERNAME}" ] && set_key "Server1.Username"    "${NZBGET_SERVER1_USERNAME}"
[ -n "${NZBGET_SERVER1_PASSWORD}" ] && set_key "Server1.Password"    "${NZBGET_SERVER1_PASSWORD}"
set_key "Server1.Port"        "${NZBGET_SERVER1_PORT:-563}"
set_key "Server1.Connections" "${NZBGET_SERVER1_CONNECTIONS:-20}"

# Bandwidth
set_key "DownloadRate" "${NZBGET_DOWNLOAD_RATE:-0}"

# Categories
IDX=1
ORDER=1
while true; do
  eval "CAT_NAME=\${NZBGET_CAT_${IDX}_NAME:-}"
  [ -z "$CAT_NAME" ] && break
  eval "CAT_DIR=\${NZBGET_CAT_${IDX}_DIR:-}"
  eval "CAT_UNPACK=\${NZBGET_CAT_${IDX}_UNPACK:-yes}"
  eval "CAT_ALIASES=\${NZBGET_CAT_${IDX}_ALIASES:-}"
  set_key "Category${ORDER}.Name"    "$CAT_NAME"
  set_key "Category${ORDER}.DestDir" "$CAT_DIR"
  set_key "Category${ORDER}.Unpack"  "$CAT_UNPACK"
  set_key "Category${ORDER}.Aliases" "$CAT_ALIASES"
  ORDER=$((ORDER + 1))
  IDX=$((IDX + 1))
done

# Tasks
IDX=1
while true; do
  eval "TASK_TIME=\${NZBGET_TASK_${IDX}_TIME:-}"
  [ -z "$TASK_TIME" ] && break
  eval "TASK_WEEKDAYS=\${NZBGET_TASK_${IDX}_WEEKDAYS:-1-7}"
  eval "TASK_COMMAND=\${NZBGET_TASK_${IDX}_COMMAND:-PauseDownload}"
  eval "TASK_PARAM=\${NZBGET_TASK_${IDX}_PARAM:-}"
  set_key "Task${IDX}.Time"     "$TASK_TIME"
  set_key "Task${IDX}.WeekDays" "$TASK_WEEKDAYS"
  set_key "Task${IDX}.Command"  "$TASK_COMMAND"
  set_key "Task${IDX}.Param"    "$TASK_PARAM"
  IDX=$((IDX + 1))
done

echo "[pre-deploy] done"
