#!/bin/sh
set -e

ENV_FILE=""
for f in .env .env.stack compose.env; do
  [ -f "$f" ] && ENV_FILE="$f" && break
done

if [ -n "$ENV_FILE" ]; then
  echo "[pre-deploy] sourcing $ENV_FILE"
  while IFS= read -r line || [ -n "$line" ]; do
    line="$(printf '%s' "$line" | tr -d '\r')"
    case "$line" in \#*|'') continue ;; esac
    key="${line%%=*}"
    value="${line#*=}"
    export "$key=$value"
  done < "$ENV_FILE"
else
  echo "[pre-deploy] no .env file found, using shell environment"
fi

NZBGET_DIR="${NZBGET_PATH_CONFIG:-./nzbget/config}"
CONF="${NZBGET_DIR}/nzbget.conf"

echo "[pre-deploy] NZBGET_PATH_CONFIG=${NZBGET_PATH_CONFIG:-<unset>}"
echo "[pre-deploy] resolved config dir: ${NZBGET_DIR}"

if [ -f "$CONF" ]; then
  echo "[pre-deploy] nzbget.conf already exists, skipping generation"
  exit 0
fi

mkdir -p "${NZBGET_DIR}"

echo "[pre-deploy] generating nzbget.conf from environment"

cat > "$CONF" <<EOF
# Generated by pre-deploy.sh — NZBGet manages this file after first start

# --- Paths ---
MainDir=${NZBGET_MAIN_DIR:-/config}
DestDir=${NZBGET_DEST_DIR:-/data/completed}
InterDir=${NZBGET_INTER_DIR:-/data/intermediate}
TempDir=${NZBGET_TEMP_DIR:-/data/tmp}
NzbDir=${NZBGET_NZB_DIR:-/config/nzb}
QueueDir=${NZBGET_QUEUE_DIR:-/config/queue}

# --- Security ---
ControlIP=0.0.0.0
ControlPort=6789
ControlUsername=${NZBGET_USER:-nzbget}
ControlPassword=${NZBGET_PASS:-}
AuthorizedIP=
FormAuth=no
SecureControl=no

# --- News Server ---
Server1.Active=yes
Server1.Name=${NZBGET_SERVER1_NAME:-newsserver}
Server1.Host=${NZBGET_SERVER1_HOST}
Server1.Port=${NZBGET_SERVER1_PORT:-563}
Server1.Username=${NZBGET_SERVER1_USERNAME}
Server1.Password=${NZBGET_SERVER1_PASSWORD}
Server1.Encryption=yes
Server1.Connections=${NZBGET_SERVER1_CONNECTIONS:-20}
Server1.Retention=0
Server1.CertVerification=strict
Server1.IpVersion=auto

# --- Connection ---
ArticleTimeout=60
DownloadRate=${NZBGET_DOWNLOAD_RATE:-0}

# --- Logging ---
WriteLog=rotate
RotateLog=3
ErrorTarget=both
WarningTarget=both
InfoTarget=both
DetailTarget=log
DebugTarget=log
LogFile=\${MainDir}/nzbget.log

# --- Post-Processing ---
ParCheck=auto
ParRepair=yes
ParScan=extended
ParQuick=yes
PostStrategy=balanced
FileNaming=auto
ParBuffer=250
ParThreads=0
DirectUnpack=yes
Unpack=yes
DirectWrite=yes
ContinuePartial=yes
ArticleCache=250
EOF

ORDER=1
IDX=1
while true; do
  eval "CAT_NAME=\${NZBGET_CAT_${IDX}_NAME:-}"
  [ -z "$CAT_NAME" ] && break
  eval "CAT_DIR=\${NZBGET_CAT_${IDX}_DIR:-}"
  eval "CAT_UNPACK=\${NZBGET_CAT_${IDX}_UNPACK:-yes}"
  eval "CAT_ALIASES=\${NZBGET_CAT_${IDX}_ALIASES:-}"
  cat >> "$CONF" <<EOF

Category${ORDER}.Name=${CAT_NAME}
Category${ORDER}.DestDir=${CAT_DIR}
Category${ORDER}.Unpack=${CAT_UNPACK}
Category${ORDER}.Aliases=${CAT_ALIASES}
EOF
  ORDER=$((ORDER + 1))
  IDX=$((IDX + 1))
done

IDX=1
while true; do
  eval "TASK_TIME=\${NZBGET_TASK_${IDX}_TIME:-}"
  [ -z "$TASK_TIME" ] && break
  eval "TASK_WEEKDAYS=\${NZBGET_TASK_${IDX}_WEEKDAYS:-1-7}"
  eval "TASK_COMMAND=\${NZBGET_TASK_${IDX}_COMMAND:-PauseDownload}"
  eval "TASK_PARAM=\${NZBGET_TASK_${IDX}_PARAM:-}"
  cat >> "$CONF" <<EOF

Task${IDX}.Time=${TASK_TIME}
Task${IDX}.WeekDays=${TASK_WEEKDAYS}
Task${IDX}.Command=${TASK_COMMAND}
Task${IDX}.Param=${TASK_PARAM}
EOF
  IDX=$((IDX + 1))
done

chown -R "${PUID:-1000}:${PGID:-1000}" "${NZBGET_DIR}" 2>/dev/null || true

echo "[pre-deploy] nzbget.conf created"
