x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: "3"

services:
  databasus:
    image: databasus/databasus:v3.59.0@sha256:90e4a1b26c54eeb2601ae5855355940aed5d80b8e0c3c6f84d5bc99960ab0ee9
    container_name: databasus
    restart: unless-stopped
    logging: *default-logging
    environment:
      - TZ=${TZ:-}
    ports:
      - "${DATABASUS_PORT:-4005}:4005"
    volumes:
      - ${DATABASUS_PATH_DATA:?DATABASUS_PATH_DATA is required}:/databasus-data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - db-net
    healthcheck:
      test: ["CMD", "databasus", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          memory: 64M

networks:
  db-net:
    external: true
