ansible_host: ENC[AES256_GCM,data:+AH027ixiSlaGfg=,iv:C3Dzgtu3sI/RYtR91ac+AAkJMCRGdX9qioEf6UOPIQo=,tag:hPPxwia2dvXgd9lZQCPqMA==,type:str]
ansible_user: ENC[AES256_GCM,data:2OVXEqM=,iv:PQUtu/Wn/tpvip5DSvFNtn7rxOJBFuvJ5O6Tad7g9DA=,tag:E4mocC3+wScm3aacQ4ig5g==,type:str]
hawser_dockhand_url: ENC[AES256_GCM,data:1qzEMWb6njEunQsVLwIYmyj1D/+bL/4PnQTQMG2TY2+PjUaMZ2UWzw==,iv:Nz7miKx6QNVBp+0KeNKaNM7DLTdwOaMufNNL+j9CyoM=,tag:17gptQo9fjPBiTazP7XHIw==,type:str]
hawser_dockhand_token: ENC[AES256_GCM,data:nACN92xzXOxLL+5+4SL9J/0gXpgVju8AOSVBR9MULNUQFgluC/QLbVNTcw==,iv:3WIu0nyXZ+aYqYmuVBNBhxZMdI5qF4aCOE1TQ7DQjQI=,tag:/aeznRjqX3qN6dtk738xxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKU0lkeXJJeFZNYWVmRzlj
            L0oxS0J3bHhYTHNZV1gvY0R6ZnVsbThNRHdBCk0vbHFLb3JiWlZPcnlPZ3dENG9i
            bW52QTZDcyt4SmRZenVTSmpwMTBLODAKLS0tIGp3T3JhMVcyNXZrQXpWNHNFbUlE
            L0VBU2U0bGVGSFJsMDFZelp3TGNVUTAK1+QBgoXEYTsMCL9ERtq3DP8c4lbcqaQH
            y8h4+vOjf5Ms+PYZ+nPSPJ9aGIX2uz0N2unkLs2EAoHC8H9KlE5DrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T16:48:31Z"
    mac: ENC[AES256_GCM,data:FGH7vx/lpz3fd1N8L7wQg11ebevmnE2WHvFi1lL8XZTv6iYG5C79azhqMwXbGMpjc8oiugJaQWKiBMHWYn2rQMpoiaFmYgEV+1jYSbeaKwYWHZ5mGtzA6t6OidXVnumxJApGxHJ9wm2faX3H+eldmeBZyJA2s1W8pIekStbNnpc=,iv:zXWmXxweSkCGAkG8Jk990oZnKuNsirLzDxFLpH60o6Y=,tag:Wzfd3au8xU4ATgZPPhSNdg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
