ansible_host: ENC[AES256_GCM,data:+AH027ixiSlaGfg=,iv:C3Dzgtu3sI/RYtR91ac+AAkJMCRGdX9qioEf6UOPIQo=,tag:hPPxwia2dvXgd9lZQCPqMA==,type:str]
ansible_user: ENC[AES256_GCM,data:2OVXEqM=,iv:PQUtu/Wn/tpvip5DSvFNtn7rxOJBFuvJ5O6Tad7g9DA=,tag:E4mocC3+wScm3aacQ4ig5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKU0lkeXJJeFZNYWVmRzlj
            L0oxS0J3bHhYTHNZV1gvY0R6ZnVsbThNRHdBCk0vbHFLb3JiWlZPcnlPZ3dENG9i
            bW52QTZDcyt4SmRZenVTSmpwMTBLODAKLS0tIGp3T3JhMVcyNXZrQXpWNHNFbUlE
            L0VBU2U0bGVGSFJsMDFZelp3TGNVUTAK1+QBgoXEYTsMCL9ERtq3DP8c4lbcqaQH
            y8h4+vOjf5Ms+PYZ+nPSPJ9aGIX2uz0N2unkLs2EAoHC8H9KlE5DrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-04T13:12:00Z"
    mac: ENC[AES256_GCM,data:Hkgc1s/BBt8tns3zZVGvX8y7I0dfguLIy3DaAQfextdVAqkG7ul9TVF+c8LciDM6xEbRVoWQ/dwIbKf9dtl9qC443if4PD1qP8+g2Ys+AUVW/7QxBvLHjgjeVtQcrx0lkrmX3ycbORLihHkEttu+ROH15nYo6LvumzeMRfWGPx0=,iv:C9ZpY6x2dx/GuEEkMoX7br3M3VOUjGBdJl7Y1AmNLx0=,tag:2/IrYPfarCVV1yAIgPBcbA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
