services:
  config-cli:
    environment:
      - KC_CLIENT_JELLYFIN_ID=${KC_CLIENT_JELLYFIN_ID}
      - KC_CLIENT_JELLYFIN_SECRET=${KC_CLIENT_JELLYFIN_SECRET}
      - KC_CLIENT_JELLYFIN_REDIRECT_URI=${KC_CLIENT_JELLYFIN_REDIRECT_URI}
      - KC_CLIENT_AUDIOBOOKSHELF_ID=${KC_CLIENT_AUDIOBOOKSHELF_ID}
      - KC_CLIENT_AUDIOBOOKSHELF_SECRET=${KC_CLIENT_AUDIOBOOKSHELF_SECRET}
      - KC_CLIENT_AUDIOBOOKSHELF_REDIRECT_URI=${KC_CLIENT_AUDIOBOOKSHELF_REDIRECT_URI}
      - KC_CLIENT_IMMICH_ID=${KC_CLIENT_IMMICH_ID}
      - KC_CLIENT_IMMICH_SECRET=${KC_CLIENT_IMMICH_SECRET}
      - KC_CLIENT_IMMICH_REDIRECT_URI_1=${KC_CLIENT_IMMICH_REDIRECT_URI_1}
      - KC_CLIENT_IMMICH_REDIRECT_URI_2=${KC_CLIENT_IMMICH_REDIRECT_URI_2}
      - KC_CLIENT_IMMICH_REDIRECT_URI_3=${KC_CLIENT_IMMICH_REDIRECT_URI_3}
      - KC_CLIENT_MEALIE_ID=${KC_CLIENT_MEALIE_ID}
      - KC_CLIENT_MEALIE_SECRET=${KC_CLIENT_MEALIE_SECRET}
      - KC_CLIENT_MEALIE_REDIRECT_URI=${KC_CLIENT_MEALIE_REDIRECT_URI}
      - KC_CLIENT_PAPERLESS_ID=${KC_CLIENT_PAPERLESS_ID}
      - KC_CLIENT_PAPERLESS_SECRET=${KC_CLIENT_PAPERLESS_SECRET}
      - KC_CLIENT_PAPERLESS_REDIRECT_URI=${KC_CLIENT_PAPERLESS_REDIRECT_URI}
      - KC_CLIENT_VAULTWARDEN_ID=${KC_CLIENT_VAULTWARDEN_ID}
      - KC_CLIENT_VAULTWARDEN_SECRET=${KC_CLIENT_VAULTWARDEN_SECRET}
      - KC_CLIENT_VAULTWARDEN_REDIRECT_URI=${KC_CLIENT_VAULTWARDEN_REDIRECT_URI}
      - KC_CLIENT_PANGOLIN_ID=${KC_CLIENT_PANGOLIN_ID}
      - KC_CLIENT_PANGOLIN_SECRET=${KC_CLIENT_PANGOLIN_SECRET}
      - KC_CLIENT_PANGOLIN_REDIRECT_URI=${KC_CLIENT_PANGOLIN_REDIRECT_URI}
      - KC_CLIENT_KOMODO_ID=${KC_CLIENT_KOMODO_ID}
      - KC_CLIENT_KOMODO_SECRET=${KC_CLIENT_KOMODO_SECRET}
      - KC_CLIENT_KOMODO_REDIRECT_URI=${KC_CLIENT_KOMODO_REDIRECT_URI}
      - KC_CLIENT_STEPCA_SECRET=${KC_CLIENT_STEPCA_SECRET}
    volumes:
      - ./realm-config/20-clients.yaml:/config/20-clients.yaml:ro
