ansible_host: ENC[AES256_GCM,data:f8zg2GN4CyV320s=,iv:QaTGsjj6uXqwDxiD1UKy0h9d9t+5GnVkJil4Tn+4iyk=,tag:jJV0ppb3BoCqJcB51pcvzQ==,type:str]
ansible_user: ENC[AES256_GCM,data:uiRwnaY=,iv:TDCPYWWCmZ6siQM++cXl1ZBQCWruyGkHjgj1ZWi19l8=,tag:Cxdy/YGGqfqlAfoOc6jxuA==,type:str]
hawser_dockhand_url: ENC[AES256_GCM,data:gz+Bt8zpYLrAH79j3qn+AuXNpM1PrUFdz/MtkHdH0J4H1GfrWnc9ew==,iv:YHNC6R5r4599J+bvDnpwOkRwBoitV9v1cCs8ChH//gs=,tag:GOFsXtECyOoPD5lwAlrnlQ==,type:str]
hawser_dockhand_token: ENC[AES256_GCM,data:qC/dd/bCCMQoZbWvWAQ+Wm1BWzjNN360zUgUbteZfhkztZd+E4sXfXy2kQ==,iv:voT+K1lnjv2Ahdub5YRLXarPBUAf3Qq9a2fjE3UFneY=,tag:3LeDJgeWOIhl8E0qB5bjEQ==,type:str]
bifrost_private_key: ENC[AES256_GCM,data:avLjv1DjOG4=,iv:l26ygcl8s82OHlJYPRs7s9tqJB0IJdfIkFmPLMCI+MM=,tag:9IOXJFuD+dyjY8c1rTkI5g==,type:str]
bifrost_address: ENC[AES256_GCM,data:u+4xqecQtl8R/k6SRg==,iv:nOc2rSe9zrIEWE4fW6/Am1HhFU0cL4R3vEB/XP6t3nc=,tag:VxDIC/QpmyLEcnDxPEX5kQ==,type:str]
bifrost_peer_public_key: ENC[AES256_GCM,data:u//caUHhlag=,iv:dgkU09m8HJe+FvcX/FzgkMfYecncNh0eA76CfzDjDR8=,tag:MGj9yFnC6IwjzdEIWkWq/g==,type:str]
bifrost_peer_endpoint: ENC[AES256_GCM,data:hQ52WLtn/2yeJOI81HcWfD5NIWuQ,iv:SfnYRW8CIPlamKAdaq42pIhw9MF4bWVhhENlx0Dofr0=,tag:cai//PprYGf3HNrQNhZ6Ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTmxyb1NrQUwxSHU5SSti
            cWlWbzl6eXRoZUpJZFdMUkxWdzd1bHdYMjJZCm5xZngvc2QxV1V0cnZsTGoxdUxw
            d29ua2NDMlhLNlVOQkhqMzNFRTFkaEUKLS0tIEUxR0F2Ty95KzVvcnRWaXhoWG9K
            ZTZpb3BHQXBiZTBKZWVVcVFFYStmeWcKpsDbwbNDngnc008/inbpAxTN1lL7FoGR
            3i5vfC0y2k68RnIGwjUtdRRG9OdNKoSPMYVlZ1P9Kyx19Bpnu57rOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T08:35:59Z"
    mac: ENC[AES256_GCM,data:178rbfYhJB33el6GFwSOswbxNxP2bLMu4/13dGucbRxjHv7OctePt8Z8liDO44qXKIrwdboxko0E8R/JWpEZDn+f60KZ+MZ85x3IS2wIWXtEng+4qcNfw5J0FiEToMDPjAVDSDBIn8iupnBeyk4oxZC+2flbKpeRBJ2htv/2Hsg=,iv:flnWZESk1Val0dDeI9Pe8aHYDJY88eWidF0duAEIjm0=,tag:tCKq3HEM5+FlEpc4B23fVA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
