apiVersion: 1

deleteContactPoints:
  - orgId: 1
    uid: discord-homelab

contactPoints:
  - orgId: 1
    name: ntfy
    receivers:
      - uid: ntfy-homelab
        type: webhook
        settings:
          url: $NTFY_WEBHOOK_URL
          httpMethod: POST
          authorization_scheme: Bearer
          authorization_credentials: $NTFY_WEBHOOK_TOKEN
