apiVersion: 1

deleteContactPoints:
  - orgId: 1
    uid: ntfy-homelab

contactPoints:
  - orgId: 1
    name: discord
    receivers:
      - uid: discord-homelab
        type: discord
        settings:
          url: $DISCORD_WEBHOOK_URL
          use_discord_username: true
          title: '{{ template "discord.title" . }}'
          message: '{{ template "discord.message" . }}'
