ansible_host: ENC[AES256_GCM,data:kxw1W0vZ8IDl+fU=,iv:VAezENZwlV4SDQ97Go4/HAMc0MMexSvih22SNSGs0I0=,tag:1Oio5a8hktTf7bA88LHLug==,type:str]
ansible_user: ENC[AES256_GCM,data:1s47MrI=,iv:Icd4TYuRowxujvCjS4hSnuBeb8Jjpg420GD7Jbfe32A=,tag:uc9Z5J8GBmbskDYOij5xkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUE5SOXFpUWFVM1JzQkdm
            OWZQUitUYU1NTkIrRXJqMDczZFZ4eVl1Y200CmZpMExFUmRQenNweSt4MThONHZh
            bHF2dXZ6Slh2S1hwUVNuMkJqekVPYTgKLS0tIFF1a28yc1VXRk1KN3Y5ZENpeGdG
            MXR0NURaZGtYSWlnSjhYUE5vL0VRamcKLLi+AEPcW2mlkOdyjjVB3u1V1R4aRe07
            12uN2rQpKQFv/UDnqT0X1KxFvZKMizOQnkVDpWs/nCPL++1Ms6UvPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T06:18:20Z"
    mac: ENC[AES256_GCM,data:gQeAt7OPdWwB4ivv9rLTSheaeKmeIzZGYvSOPpxrPVd3nW5s/To32tMHsaGkMHhtCZMHY741Bh8u4eEaiVQxVRtlqvaJk/PGM6ppffo9Ii9oIXzeT4pFOClVDrhXM7hr9A7cGvap0Ua//R0aAmh7FbfCVlF0DWxfufTgKyNaAXY=,iv:cPqjpUdOCs6jZ43BDuPM5INZgDCLpF2JUnxVH4lJ5us=,tag:YoLFdh7jzHZgdeBIlH9LFw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
