x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: "3"

services:
  server:
    image: ghcr.io/goauthentik/server:2026.5.6
    container_name: authentik-server
    restart: unless-stopped
    logging: *default-logging
    command: server
    environment:
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY:?AUTHENTIK_SECRET_KEY is required}
      - AUTHENTIK_POSTGRESQL__HOST=${PG_HOST:-authentik-db}
      - AUTHENTIK_POSTGRESQL__USER=${PG_USER:-authentik}
      - AUTHENTIK_POSTGRESQL__NAME=${PG_DB:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${PG_PASS:?PG_PASS is required}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    ports:
      - "${AUTHENTIK_PORT_HTTP:-9000}:9000"
      - "${AUTHENTIK_PORT_HTTPS:-9443}:9443"

  worker:
    image: ghcr.io/goauthentik/server:2026.5.6
    container_name: authentik-worker
    restart: unless-stopped
    logging: *default-logging
    command: worker
    environment:
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY:?AUTHENTIK_SECRET_KEY is required}
      - AUTHENTIK_POSTGRESQL__HOST=${PG_HOST:-authentik-db}
      - AUTHENTIK_POSTGRESQL__USER=${PG_USER:-authentik}
      - AUTHENTIK_POSTGRESQL__NAME=${PG_DB:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${PG_PASS:?PG_PASS is required}
    volumes:
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
