x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: "3"

services:
  vaultwarden:
    image: vaultwarden/server:1.37.0@sha256:e6443e3d5ed8fcee2204b89ec778d7f24d0173bcc42d1ea34f990304f5f63f51
    container_name: vaultwarden
    restart: unless-stopped
    logging: *default-logging
    environment:
      - TZ=${TZ:-}
      - PUID=${PUID:-}
      - PGID=${PGID:-}
      - DOMAIN=${VW_DOMAIN:-}
      - DISABLE_ADMIN_TOKEN=${VW_DISABLE_ADMIN_TOKEN:-true}
      - SIGNUPS_ALLOWED=${VW_SIGNUPS_ALLOWED:-false}
      - DATABASE_URL=${VW_DATABASE_URL:-}
    volumes:
      - ${VW_PATH_DATA:?VW_PATH_DATA is required}:/data/
    ports:
      - "${VW_PORT:-3002}:80"
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 256M
        reservations:
          memory: 128M
