x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: "3"

services:
  vaultwarden:
    image: vaultwarden/server:1.37.0
    container_name: vaultwarden
    restart: unless-stopped
    logging: *default-logging
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - DOMAIN=${VAULTWARDEN_DOMAIN:-}
      - DISABLE_ADMIN_TOKEN=${DISABLE_ADMIN_TOKEN:-true}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED:-false}
      - DATABASE_URL=${DATABASE_URL:-}
    volumes:
      - ${VAULTWARDEN_DATA_PATH:-./data}:/data/
    ports:
      - "${VAULTWARDEN_PORT:-3002}:80"
