x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: "3"

services:
  vaultwarden:
    image: vaultwarden/server:1.37.2@sha256:094b5689ed81549bd293418395c7cf495ae9d960fc2d4928cef2083ef913d912
    container_name: vaultwarden
    restart: unless-stopped
    logging: *default-logging
    environment:
      - TZ=${TZ:-}
      - PUID=${PUID:-}
      - PGID=${PGID:-}
      - DOMAIN=${VW_DOMAIN:-}
      - DISABLE_ADMIN_TOKEN=${VW_DISABLE_ADMIN_TOKEN:-true}
      - SIGNUPS_ALLOWED=${VW_SIGNUPS_ALLOWED:-false}
      # DB
      - DATABASE_URL=${VW_DB_ENGINE:-postgresql}://${VW_DB_USER:?VW_DB_USER is required}:${VW_DB_PASS:?VW_DB_PASS is required}@${VW_DB_HOST:?VW_DB_HOST is required}:${VW_DB_PORT:-5432}/${VW_DB_NAME:?VW_DB_NAME is required}
      - DATABASE_MAX_CONNS=${VW_DATABASE_MAX_CONNS:-10}
      - WEBSOCKET_ENABLED=${VW_WEBSOCKET_ENABLED:-true}
      # SSO
      - SSO_ENABLED=${VW_SSO_ENABLED:-false}
      - SSO_ONLY=${VW_SSO_ONLY:-false}
      - SSO_AUTHORITY=${VW_SSO_AUTHORITY:-}
      - SSO_CLIENT_ID=${VW_SSO_CLIENT_ID:-}
      - SSO_CLIENT_SECRET=${VW_SSO_CLIENT_SECRET:-}
      # SMTP
      - SMTP_HOST=${VW_SMTP_HOST:-}
      - SMTP_PORT=${VW_SMTP_PORT:-587}
      - SMTP_SECURITY=${VW_SMTP_SECURITY:-starttls}
      - SMTP_FROM=${VW_SMTP_FROM:-}
      - SMTP_FROM_NAME=${VW_SMTP_FROM_NAME:-Vaultwarden}
      - SMTP_USERNAME=${VW_SMTP_USER:-}
      - SMTP_PASSWORD=${VW_SMTP_PASS:-}
      - SMTP_AUTH_MECHANISM=${VW_SMTP_AUTH_MECHANISM:-Plain}
      - SMTP_TIMEOUT=${VW_SMTP_TIMEOUT:-15}
      - SMTP_ACCEPT_INVALID_CERTS=${VW_SMTP_ACCEPT_INVALID_CERTS:-false}
      - SMTP_ACCEPT_INVALID_HOSTNAMES=${VW_SMTP_ACCEPT_INVALID_HOSTNAMES:-false}
      - SMTP_EMBED_IMAGES=${VW_SMTP_EMBED_IMAGES:-true}
      - SMTP_DEBUG=${VW_SMTP_DEBUG:-false}
      - HELO_NAME=${VW_SMTP_HELO_NAME:-}
    volumes:
      - ${VW_PATH_DATA:?VW_PATH_DATA is required}:/data/
    ports:
      - "${VW_PORT:-3002}:80"
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 256M
        reservations:
          memory: 128M
