ansible_host: ENC[AES256_GCM,data:hj+X9w14R8lGKks=,iv:K+6xoDw/uMi26HPp0uoiW/He6WLAk/CS+XviYUnHJ64=,tag:llweZoA5uCDpnrFuD42/YQ==,type:str]
ansible_user: ENC[AES256_GCM,data:nS6yO34=,iv:IREZqkrT4Q9y7iY4aCN3K4S4GZTTFmKGWd4w1lgtYr8=,tag:2M6QZj7IYoHLpC7L0W+kRw==,type:str]
komodo_bind_ip: ENC[AES256_GCM,data:8AaOAW9OXQ==,iv:hfpfjpi0YG/fAuIKm+DizOOZWiUrfSlPlDLZaB4PW4Q=,tag:RldjyLg6kQgHWig3wrsRIw==,type:str]
komodo_database_address: ENC[AES256_GCM,data:3MsxaG0rZOpniGBtDfZkx7c=,iv:vvQvzllSHQhku0ykdk8n3GngfkGQph9AO6/2NWYkh20=,tag:nj8JmH1ae33qHFJtDPw85g==,type:str]
komodo_db_username: ENC[AES256_GCM,data:BoysLQc=,iv:Q8B4DIKxsuJJ/WSih9CuMxA17z2ZN4cn6QrZPp1h8HQ=,tag:pWAAcq4PtDfUZ9eNQ8uPIg==,type:str]
komodo_db_password: ENC[AES256_GCM,data:h8IKiHI=,iv:MZvwJCLXsGQX8LySlzTvuQCOnHHvaPvApy8LcXXqu5A=,tag:ttE2Cy4FsOllQzhikrcbOQ==,type:str]
komodo_admin_password: ENC[AES256_GCM,data:G2/U/Aij6kHuadFIWnnJgsMhRWoPppuHYhid,iv:huASe3CxVnDL4I6dZskoKjoB/NQbCKqfuNgs8zx4MsE=,tag:olAaIZcf1uep4onA+iCNfg==,type:str]
komodo_jwt_secret: ENC[AES256_GCM,data:U0a9z6l3AcZNRKkbfgeYDSvuH5EleiX7Sby8nRgdWHzVsuuMe+GSsiyCgg==,iv:XiMH39g6EvYPtJ7c5gWUcgaBkryfS0NnevGCHmlspZ0=,tag:g4gTIjsp2P3M54BaS3ydwA==,type:str]
komodo_webhook_secret: ENC[AES256_GCM,data:r26+gMYUj+PVqoNhft3MIxK4cMGusKgKqESJ+74qiT5RUQvQuZqbGwmm1w==,iv:EF/cZK5dZ7PJ/qQNQFoY89rwSsgr8MgjmVYTQEh9gOo=,tag:L/n/ov4zCerdl+8du2ttgg==,type:str]
komodo_host: ENC[AES256_GCM,data:U0LSWow+hPKaslC/qQSgjLqDQp5dbDo=,iv:OzLhEuSOJr7XOM0zgPYhQy0R8+TYEzhESpveliVGMGE=,tag:WxLgEd1roOEt5xGhOMQWXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdmFkVTVCSnFHM0orY1dx
            TmtHVDJVWVpwaW9uV2N2MkwxVWhZdmJzNHo0Cm1IRElKK05HaGRxaW8zaHpvNHlo
            N2dzQUJwV0d3WjMwbC9wdVExVGg1cTgKLS0tIDJHREh6TFB3ZEVkTHBKLzNQbzFO
            RCs0Y1RCK2Y3VlpNeVBUZlo3RzR5SXMKGiAaEn6wdP0ady1M9PxkuttnUKHjeW9X
            cb6xt2MdZ8nxz23po4MtHjGIniUzrjibasyczxq6xeMx9lPY4SKJgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
    lastmodified: "2026-08-24T13:41:43Z"
    mac: ENC[AES256_GCM,data:K4XzGXOureMF8oRVcetYChWjGCnWG1DsYPUxjwiNMBW00mPcmQ715z5zmEa9sF/6bJz5HAi/cSmfIIV5kT1P5DV1aWtEuYMJ4Dwjj0n/M2PZx06X55z3ZxZPsy3J4LOCUkBF42RDG7DkZz/8RQdvcstxQIgWytTpt695I0Myv+U=,iv:YPhPaGc4UrvZNWK5kIZ+JODXq6m8yoTNKatwSize9Io=,tag:Aly1NOMjdGaR4EYwxB1u1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
