services:
  alloy:
    volumes:
      - ../../alloy/features/media.alloy:/etc/alloy/media.alloy
    environment:
      - JELLYFIN_METRICS_TARGET=${ALLOY_JELLYFIN_METRICS_TARGET:-jellyfin:8096}
    networks:
      - default
      - media-net

networks:
  media-net:
    external: true
