services:
  alloy:
    depends_on:
      nut-exporter:
        condition: service_started
    networks:
      - nut-net

  nut-exporter:
    image: druggeri/nut_exporter:3.3.0
    container_name: nut-exporter
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - NUT_EXPORTER_PASSWORD=${ALLOY_NUT_EXP_PASS:?ALLOY_NUT_EXP_PASS is required}
    command:
      - --nut.server=${ALLOY_NUT_EXP_SERVER:?ALLOY_NUT_EXP_SERVER is required}
      - --nut.serverport=${ALLOY_NUT_EXP_SERVER_PORT:-3493}
      - --nut.username=${ALLOY_NUT_EXP_USER:?ALLOY_NUT_EXP_USER is required}
    networks:
      - nut-net
    deploy:
      resources:
        limits:
          cpus: 0.10
          memory: 64M
        reservations:
          memory: 32M

networks:
  nut-net:
    external: true
