# ── FeelsCozyMan ──────────────────────────────────────────────────────────

# [[stack]]
# name = "FeelsCozyMan-homeassistant"
# tags = ["iot"]
# [stack.config]
# server = "FeelsCozyMan"
# run_directory = "stacks/homeassistant"
# file_paths = ["compose.yml"]
# linked_repo = "homelab-infra"
# extra_args = ["--remove-orphans"]
# environment = """
# TZ=[[tz]]
# """
#
# [[stack.config.additional_env_files]]
# path = "homeassistant.env"
# contents = """
# HA_VLAN_IP=[[FeelsCozyMan_ha_vlan_ip]]
# HA_VLAN_SUBNET=[[FeelsCozyMan_ha_vlan_subnet]]
# HA_SERIAL_DEVICE=/dev/serial1
# HA_PORT=8123
# HA_MAC_DEFAULT=02:42:ac:11:00:02
# HA_MAC_VLAN=02:42:ac:12:00:02
# HA_VLAN_PARENT=vlan88
# HA_PATH_CONFIG=/docker/homeassistant/data
# """
#
# [[stack.config.additional_env_files]]
# path = "mqtt.env"
# contents = """
# MQTT_PORT=8124
# MQTT_PATH_CONFIG=/docker/homeassistant/mosquitto/config
# MQTT_PATH_DATA=/docker/homeassistant/mosquitto/data
# MQTT_PATH_LOG=/docker/homeassistant/mosquitto/log
# """
#
# [[stack.config.additional_env_files]]
# path = "zigbee-matter.env"
# contents = """
# Z2M_PORT=8125
# Z2M_PATH_DATA=/docker/homeassistant/zigbee2mqtt/data
# MATTER_LOG_LEVEL=info
# MATTER_BLE_PROXY=true
# MATTER_PATH_DATA=/docker/homeassistant/matter/data
# """
#
# [[stack.config.additional_env_files]]
# path = "njord.env"
# contents = """
# NJORD_PORT=9090
# NJORD_HEALTH_PORT=9091
# NJORD_POLL_INTERVAL=01:00:00
# NJORD_FORECAST_DAYS=7
# NJORD_LOCATION_NAME=changeme
# NJORD_LOCATION_LAT=changeme
# NJORD_LOCATION_LON=changeme
# """
#
# [[stack]]
# name = "FeelsCozyMan-vaultwarden"
# tags = ["infra"]
# [stack.config]
# server = "FeelsCozyMan"
# run_directory = "stacks/vaultwarden"
# file_paths = ["compose.yml"]
# linked_repo = "homelab-infra"
# extra_args = ["--remove-orphans"]
# environment = """
# VW_DOMAIN=[[FeelsCozyMan_vaultwarden_domain]]
# VW_DATABASE_URL=[[FeelsCozyMan_vaultwarden_database_url]]
# PUID=[[puid]]
# PGID=[[pgid]]
# TZ=[[tz]]
# VW_DISABLE_ADMIN_TOKEN=true
# VW_SIGNUPS_ALLOWED=false
# VW_PORT=3002
# VW_PATH_DATA=/docker/vaultwarden/data
# """
