# ── FeelsDevMan ───────────────────────────────────────────────────────

[[stack]]
name = "alloy-2"
tags = ["monitoring"]
[stack.config]
server = "FeelsDevMan"
project_name = "alloy-2"
run_directory = "stacks/alloy"
file_paths = ["compose.yml"]
linked_repo = "homelab-infra"
extra_args = ["--remove-orphans"]
environment = """
TZ=[[tz]]
ALLOY_REMOTE_WRITE_URL=[[metrics_remote_write_url]]
ALLOY_LOGS_PUSH_URL=[[metrics_logs_push_url]]
ALLOY_HOSTNAME=FeelsDevMan
ALLOY_SCRAPE_INTERVAL=30s
CADVISOR_HOUSEKEEPING_INTERVAL=30s
CADVISOR_DOCKER_ONLY=true
CADVISOR_DISABLE_METRICS=advtcp,cpu_topology,cpuset,hugetlb,memory_numa,process,referenced_memory,resctrl,sched,tcp,udp
"""

[[stack.config.config_files]]
path = "../../alloy/modules/appsec.alloy"
requires = "Redeploy"

[[stack.config.config_files]]
path = "../../alloy/modules/caddy.alloy"
requires = "Redeploy"

[[stack.config.config_files]]
path = "../../alloy/modules/crowdsec.alloy"
requires = "Redeploy"

[[stack.config.config_files]]
path = "../../alloy/modules/fail2ban.alloy"
requires = "Redeploy"

[[stack.config.config_files]]
path = "../../alloy/modules/honeypot.alloy"
requires = "Redeploy"

[[stack.config.config_files]]
path = "../../alloy/modules/security.alloy"
requires = "Redeploy"

[[stack.config.config_files]]
path = "../../alloy/modules/ssh.alloy"
requires = "Redeploy"

[[stack.config.config_files]]
path = "../../alloy/modules/sudo.alloy"
requires = "Redeploy"

[[stack.config.config_files]]
path = "../../alloy/modules/syslog.alloy"
requires = "Redeploy"

[[stack.config.config_files]]
path = "../../alloy/modules/ufw.alloy"
requires = "Redeploy"
