# ── FeelsNoSponsorMan ─────────────────────────────────────────────────────

[[stack]]
name = "blocky-1"
tags = ["infra"]
[stack.config]
server = "FeelsNoSponsorMan"
run_directory = "stacks/blocky"
file_paths = ["compose.yml"]
linked_repo = "homelab-infra"
extra_args = ["--remove-orphans"]
environment = """
BLOCKY_PORT_DNS=53
BLOCKY_PORT_HTTP=4000
BLOCKY_CONFIG_PATH=/docker/blocky/config.yml
"""

[[stack.config.config_files]]
path = "config.yml"
requires = "Redeploy"
