unattended_upgrades_enabled: false
unattended_upgrades_blacklist: []
unattended_upgrades_skip_reboot_required: false
unattended_upgrades_auto_reboot: false
unattended_upgrades_auto_reboot_time: "04:00"
unattended_upgrades_mail: ""
