x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: "3"

services:
  nut-upsd:
    image: instantlinux/nut-upsd@sha256:b516bfa03744b568d2440da3db0246adbcead9c56d5a122446e5592c86e76787
    container_name: nut-upsd
    restart: unless-stopped
    logging: *default-logging
    environment:
      - PUID=${PUID:-}
      - PGID=${PGID:-}
      - TZ=${TZ:-}
      - DRIVER=${NUT_DRIVER:?NUT_DRIVER is required}
      - NAME=${NUT_NAME:-ups}
      - PORT=${NUT_DRIVER_PORT:-auto}
      - POLLINTERVAL=${NUT_POLL_INTERVAL:-15}
      - API_USER=${NUT_API_USER:?NUT_API_USER is required}
      - API_PASSWORD=${NUT_API_PASS:?NUT_API_PASS is required}
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "${NUT_PORT:-3493}:3493"
    volumes:
      - ${NUT_PATH_CONFIG:?NUT_PATH_CONFIG is required}:/etc/nut
    networks:
      - nut-net
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 64M
        reservations:
          memory: 32M

networks:
  nut-net:
    name: nut-net
