ansible_host: ENC[AES256_GCM,data:+6mvEnNSdsqmn70=,iv:JENf6UVOHM8Y3ZkAUyIOrCWZC73EJ+dWuHiiX7akfl0=,tag:iFFHco6GTzNCpCKBzcsQbw==,type:str]
ansible_user: ENC[AES256_GCM,data:Lc6V5WE=,iv:C1wWpSgZRNFumrORo9DF/paLshgNLBVmzvH413I60I8=,tag:N1i+8jgnbf28eKoxz9j5CA==,type:str]
hawser_dockhand_url: ENC[AES256_GCM,data:TNR3uLKaFcuvK/ncijVyi9grpFg=,iv:N0KfWUn6uH7uXyL6ljQZW+h1E0xS2RU6ieaVcvnQGk8=,tag:6qjV4LTV6jn5qz6fDYr9Bw==,type:str]
hawser_dockhand_token: ENC[AES256_GCM,data:rTdz2ICGfcY=,iv:XLwaTeP8J+QT80S9yqiK1xw+FNqwR6oJkoT5+G6amBQ=,tag:WaIY1nODLxLF6c9hM+p7rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTzNmSVhNMkRTaHVibDRG
            Q3ZKWXRpL3ZoVHUxRW9pdVM1YVdMS25tRkE4CngwZjNYajdpTGlBSFNZc0F5RG82
            OG1RbzNQdVJQYzUxODljY2QzSWFOc1UKLS0tIFR4TXBlbElma3NBU0krN3M2RERG
            eFRYdzJiUEJPdzM3L2tRZEhHQ3dkb1kK+tjqQ/N4hjTNJD4gT149PzhAqm/+nxiy
            mNiB5FbdOHErKWNgOdkaMnvGn/LH7F6U869eDv9z/ER2/Fn2YmxLAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T16:48:31Z"
    mac: ENC[AES256_GCM,data:hTiRPlwYtPcZP3Igo3fxPQ6P8IpAu/xq3smW/Zq0bNmksexJZAjbOKfqJFmHeiT85aNPke3gfl/RK9N8hWAQi3yquxpifh1CrbFYOVP+1oaECGSJi2dlYBQoFfHv8k4T2xyhdFj4zSUntwHrseXmtewRS3fefVPrLgebP9+/w/8=,iv:jxBlPUZDG0bxMJ3EixFPx5k32q+YUIXhH3+RO9uzmHA=,tag:UVSspIbydoXbW972a8iJMw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
