ansible_host: ENC[AES256_GCM,data:+6mvEnNSdsqmn70=,iv:JENf6UVOHM8Y3ZkAUyIOrCWZC73EJ+dWuHiiX7akfl0=,tag:iFFHco6GTzNCpCKBzcsQbw==,type:str]
ansible_user: ENC[AES256_GCM,data:Lc6V5WE=,iv:C1wWpSgZRNFumrORo9DF/paLshgNLBVmzvH413I60I8=,tag:N1i+8jgnbf28eKoxz9j5CA==,type:str]
pve_exporter_pve_token_id: ENC[AES256_GCM,data:dtdhTrhZcnRahqcEMXzHx8Pn1uO7P0biMw==,iv:I8AXm5swvYk3j8OTBSjx54LDcIhP+N9N4IG8gwEnWQw=,tag:2QN2AbKThEQDzv0A5eZCGw==,type:str]
pve_exporter_pve_token_secret: ENC[AES256_GCM,data:qNzQvYsCMK1ESaZWxHgr7MSDwdNwRtBzc2rfy25/mXgVCPdt,iv:M3w7skqFWYSd0zV3mvwHyKkhX8kYqK4iGvXi9nPSrE0=,tag:gISyyWoLkcdb5Qr1meiitw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTzNmSVhNMkRTaHVibDRG
            Q3ZKWXRpL3ZoVHUxRW9pdVM1YVdMS25tRkE4CngwZjNYajdpTGlBSFNZc0F5RG82
            OG1RbzNQdVJQYzUxODljY2QzSWFOc1UKLS0tIFR4TXBlbElma3NBU0krN3M2RERG
            eFRYdzJiUEJPdzM3L2tRZEhHQ3dkb1kK+tjqQ/N4hjTNJD4gT149PzhAqm/+nxiy
            mNiB5FbdOHErKWNgOdkaMnvGn/LH7F6U869eDv9z/ER2/Fn2YmxLAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T07:06:41Z"
    mac: ENC[AES256_GCM,data:VUMM+8evAXlu4cuNv3Ur6PSjoMeNyI0gc8B/y2tIsvWT6rBCmM1zZf92DR65QvOIAkZabNl3gt8Qp5SkNgVnAGlM7tuOpC1GJlOdwgHes+W7aaR221USeCO9YpEw8DgXB+d922W6nJUu+MYMiiyYfV+djOSSJnr3mn1CqGLaXLo=,iv:geQYRfWuesFufsvE9w5DNFCb9SMzLDN6yjRKbOcBG0o=,tag:zQLI9a/VD1DmrIg39iC8cw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
