ansible_host: ENC[AES256_GCM,data:rQy96mrJYpG/PP0=,iv:graVETNbcOIaaLa5qr+ng3gD3as6Pl9iQQDwUX9SmTI=,tag:V6hVe2ZwEFknrVQjTSCv4A==,type:str]
ansible_user: ENC[AES256_GCM,data:uV7XM7U=,iv:iQOP/rYSvNUK3HWzgJlk2zzBhy+OTHpYVnzsX3FlVEw=,tag:phNgW6JipPrE/VgucS+IGA==,type:str]
hawser_dockhand_url: ENC[AES256_GCM,data:eZn6oL4yV5vEvLDVcTf9yel553ZLKBwlyBU+xwNa4CvleW1ihv6hTg==,iv:8gd9aOOViEbk/k/bzCLvZCFthdo8d5w1fRsBpjbpLnw=,tag:2OTje5VDXZBtcLMDZwmveA==,type:str]
hawser_dockhand_token: ENC[AES256_GCM,data:fSrohaHGG6kRotfgzh7m75Qg5nTApB9YBHjSqq1HKeHqd75tZWF8MxuP0Q==,iv:R4RXsIbTx2rZxzCBUzXgZfKG7SGAd5gUzyJkDYm1oXg=,tag:qvFHBsUm+cPY7GrMLy0HrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdnR1eVVjWXFvbXFUckpj
            WEl3UmxoK3ZiS1BnQ0plN285MVBtQlRoYmhNCjNXbkpVQ1dOOExDUGtxdGNyTStB
            MmkyblJoRHJoTkpwRStuZHlnL3NONXcKLS0tIGhyM2NlWkxxOERiUkZBMjZsbDI2
            akJ5TVE2R3VqRlJ1eitCNVNJL2ZDVTgKzNXH1dohrU5PUh37mkqNovVAJ8W2SUib
            mwG56eRs/igIiWL+4mREV/r++6JsdaIKXk7mInu5g9Qe6WkCRnEP1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T17:03:47Z"
    mac: ENC[AES256_GCM,data:8mq0+bhkfvZ4r3J+1YpVyXO9hDuHtnsUNAZMEm3Ov2QktMOaD/erGrCSZI4oNuMq+Yttpt4RbjrkgH/Q3Xtn/uyA/P2v/6NqiQD6GFX4o/gCfgImEgtAeh1dk4lhg4Z0P1EzYS4qSLxMCqRWypqgb0oadnjPXsHx9mW3YjYrjrU=,iv:3GgZfJn6YJFXk5VdqirGDzValdM9Hi6F9pPlPhDn92M=,tag:5JjVaGeZtW2I7PfXD+BeTQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
