ansible_host: ENC[AES256_GCM,data:DGGbahpGnhcQo1k=,iv:BSIXgsd0qWcLhzXR264iq9FpSKoY0wEJB4KVsEZe0nU=,tag:8+MWNId3t/MXmewYnwKU3A==,type:str]
ansible_user: ENC[AES256_GCM,data:f3/mt20=,iv:zKnCDjacgf2aY34wf9eUoExGtVDEEv1kgNzgn5befhA=,tag:Ydf3iqAJ+11TVdHQ3Hpv1w==,type:str]
pve_exporter_pve_token_id: ENC[AES256_GCM,data:9gumO30p3SokB0/y2cuJtoOi3tHWaP8oRQ==,iv:rnAtHgKAmXzrgq8E+gsfLhOW5zToSqmXeJKvEryBtTw=,tag:wPU+AhUALnDsh15Y8TmrNw==,type:str]
pve_exporter_pve_token_secret: ENC[AES256_GCM,data:FtUTxT0UyeIPaN9ee5Af5mTPjd4VphNkeYXLnW0cZQ8AS/Of,iv:xPko3S3QOrlagzdVtp7OV/pSRqVqxUeHkPUDm0BBAzM=,tag:Pzswk55HEm0wL+oYQZOc5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWXMxd0F5YkRqdzdlZDF3
            b2RmSVVyS0VFd1E1b3NiYVNFOUx3U005TGlvCmw1c0FQYzRmTFpkWW9ocFNJV2Np
            dFBmN1c5T2xhTVNOVktkdVErWFBLNEkKLS0tIHVwanlNUWdoSXIwQjZHK3lOYXEv
            SzQ0MHkzWVU4M2Y0dHNPMmVnWDJPaDAKBEP6nkkuDt/6c1tIR2Rg7McOJxPdWUSo
            DrkaTThGNxNHfhsYa01uS0xD+7G2x9+AUXmy+TUuS6UxVV5CXLAAKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T15:31:25Z"
    mac: ENC[AES256_GCM,data:FW69ukX2v6CJQ9kryiUFPysxYJ6rxb0hsRg6153BqEBt9CVRc0DwELvnCn3ddTNMYYFvnC5U69lqdelWQUDvOqsJPTrWp0iMh9s7AFEc7TOaXBB2T7ktzHvP+trJyIg5FHKHk6A7c9hwJVQ3i1Fc0v0F8ZNlGNHL+aIB37hY7Z0=,iv:ZlPCXwT0YLxffGCY9+U3nIr2Q2x3M7DrRt22ywG8n0Q=,tag:VuKJSsQtmoindRsPLoYhEw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
