ansible_host: ENC[AES256_GCM,data:eMzUdl9j+6qEsJ0=,iv:5UNZr9cn+Q2boTsPcH5XTkHBlnbTLd0ZT1vVvi2uRQU=,tag:c3DHhcaULt4FT817QRCqGg==,type:str]
ansible_user: ENC[AES256_GCM,data:f3/mt20=,iv:zKnCDjacgf2aY34wf9eUoExGtVDEEv1kgNzgn5befhA=,tag:Ydf3iqAJ+11TVdHQ3Hpv1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWXMxd0F5YkRqdzdlZDF3
            b2RmSVVyS0VFd1E1b3NiYVNFOUx3U005TGlvCmw1c0FQYzRmTFpkWW9ocFNJV2Np
            dFBmN1c5T2xhTVNOVktkdVErWFBLNEkKLS0tIHVwanlNUWdoSXIwQjZHK3lOYXEv
            SzQ0MHkzWVU4M2Y0dHNPMmVnWDJPaDAKBEP6nkkuDt/6c1tIR2Rg7McOJxPdWUSo
            DrkaTThGNxNHfhsYa01uS0xD+7G2x9+AUXmy+TUuS6UxVV5CXLAAKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
    lastmodified: "2026-08-24T13:48:50Z"
    mac: ENC[AES256_GCM,data:GRwAinAbuwWAtxPxQaq1X1bHq/bALgbIO1bSFRBjZXcctfYtzdU4nKXy8q+mfkTx8XK2fyjL7n3z6wfzFw1IPqdk5JoBMrPHlJjkqI3q31fu8tNK4e8aWCISL3KadqeCtEWCS+eb7Zh28tPYAAGi9EmbTGpaWAXK8S4EXil3ZlA=,iv:o9t9WzhpOUXkwaNRJ3/vrcGPGKAgUsmeKflc50VSrck=,tag:GmhRiDCO8hTgt4rUTLegmw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
