ansible_host: ENC[AES256_GCM,data:DGGbahpGnhcQo1k=,iv:BSIXgsd0qWcLhzXR264iq9FpSKoY0wEJB4KVsEZe0nU=,tag:8+MWNId3t/MXmewYnwKU3A==,type:str]
ansible_user: ENC[AES256_GCM,data:f3/mt20=,iv:zKnCDjacgf2aY34wf9eUoExGtVDEEv1kgNzgn5befhA=,tag:Ydf3iqAJ+11TVdHQ3Hpv1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWXMxd0F5YkRqdzdlZDF3
            b2RmSVVyS0VFd1E1b3NiYVNFOUx3U005TGlvCmw1c0FQYzRmTFpkWW9ocFNJV2Np
            dFBmN1c5T2xhTVNOVktkdVErWFBLNEkKLS0tIHVwanlNUWdoSXIwQjZHK3lOYXEv
            SzQ0MHkzWVU4M2Y0dHNPMmVnWDJPaDAKBEP6nkkuDt/6c1tIR2Rg7McOJxPdWUSo
            DrkaTThGNxNHfhsYa01uS0xD+7G2x9+AUXmy+TUuS6UxVV5CXLAAKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T16:17:26Z"
    mac: ENC[AES256_GCM,data:OR39usYTnqDucjLGYhk8anL6o+MmDTliGk1Z5sYhos2Qpv0zTmWeDWgFHpFLe6qs2qSJU8k/gRP7uLM181gGi3yO7tAyzAHnf0oRcKHPqE/Ba2Ug/X+Vugvrn/VCrJYG48GQ8QKaI8nQx0zimS/0hc7989jHdZkwgYUe3hezYh8=,iv:zs2pBUEjumU2Bfz9+c3l+27AcgbUhSuLOL3PuCzIFIg=,tag:60QOhgkYQxn63uXClZt7wA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
