- name: Disable ufw when disabled
  community.general.ufw:
    state: disabled
  failed_when: false
  when: not ufw_enabled

- name: Skip if ufw disabled
  ansible.builtin.meta: end_role
  when: not ufw_enabled

- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Include LXC tasks
  ansible.builtin.include_tasks: lxc.yml
  when: ufw_disable_sysctl

- name: Include standard tasks
  ansible.builtin.include_tasks: standard.yml
  when: not ufw_disable_sysctl
