- name: Set default incoming policy
  community.general.ufw:
    direction: incoming
    default: "{{ ufw_default_incoming }}"

- name: Set default outgoing policy
  community.general.ufw:
    direction: outgoing
    default: "{{ ufw_default_outgoing }}"

- name: Apply default rules
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port | string }}"
    proto: "{{ item.proto | default('tcp') }}"
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ ufw_rules + ufw_extra_rules }}"

- name: Enable ufw
  community.general.ufw:
    state: enabled
