x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: "3"

services:
  postgres:
    image: postgres:17.10-alpine@sha256:742f40ea20b9ff2ff31db5458d127452988a2164df9e17441e191f3b72252193
    container_name: postgres
    restart: always
    logging: *default-logging
    environment:
      - POSTGRES_USER=${PG_USER:-}
      - POSTGRES_PASSWORD=${PG_PASS:?PG_PASS is required}
      - POSTGRES_DB=${PG_DB:-}
      - TZ=${TZ:-}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - ${PG_PATH_DATA:?PG_PATH_DATA is required}:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command:
      - "postgres"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"
      - "-c"
      - "listen_addresses=*"
      - "-c"
      - "password_encryption=scram-sha-256"
    networks:
      - db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
        reservations:
          memory: 256M

networks:
  db-net:
    external: true
