ansible_host: ENC[AES256_GCM,data:8eLty6vjbS4vEwo=,iv:BAVuj6eg01jCB7q/fdt54rOkT9S/WPC9qqrrJMRnurw=,tag:wB2kHfmxnUPSnAqMpSElWQ==,type:str]
ansible_user: ENC[AES256_GCM,data:zqXQfjE=,iv:DiiWoJcfJxjucUMlEsRnRNGVPlydUU/NEo5T3iy/NAU=,tag:rPA3jrDqbcBowo9ezhbeVw==,type:str]
hawser_dockhand_url: ENC[AES256_GCM,data:7k1GQoW/i8ryobGAiWaEdC+6tWVXUjeXMcEdnXVcUGeHjp2yzSix1g==,iv:UWmZgFjb7/gs9II0demtgqgFdNqqQz/KCYZw7yvEv2w=,tag:2x8eRdsO9y0gRSA0BKjxxA==,type:str]
hawser_dockhand_token: ENC[AES256_GCM,data:xROq3Vw1Rz5bzRJ0A5rYZTRfs9wvPncGS9t1c+ZNx3PeBULqyBjLHIKo9g==,iv:shJ2mwcbKTWCc1o0WrZ+cMPIIzR/zBFrcMRoUOMVdqE=,tag:JAFgHKV2jU4vshsYMpjvPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOUNMWWN2RjZ0REJVKzBo
            cU9pRXZCcUlFTjdnc2RuYk15aDk5L1dET2trCms0M0J1NHlIU1p1M1VWbFdMUEZ5
            ZWs2K2tHcHF0MXFtV3VFMUxxSURNKzQKLS0tIHQ3OFR0cUcyRVRMUEgyQytsRVNq
            S1NXRFF6cTdKOUJpY1l4Qkdla1NLWUEKDq/MP7rrde6U4vcrXd6BzDzLOPKQcYtW
            b2YFyqEMNdzplsA6OfHLiGThxCGLNCSSXS4vApMK2VSZAffYaLKztw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T16:48:31Z"
    mac: ENC[AES256_GCM,data:vZIGeVvMuEGGuDs7hz3LvjDO5ueOzm/CowdG6aubAquubIgz1ZGrsRgjXZkRingGDZ+4WYk99RnYQH0ifOtfquMDLPNIH9guIegntZUiQTB16rpfpOK9/vPksZu+e7fzMQBFST0wJ0RJs454xvnwO9Crri/P//OCSWFZNtPdTbk=,iv:hDjHPcGeuCiho6Xt5OrbyrLM3yvCJ8v1YP/97QHQL1Y=,tag:3r1AdxEJV70TnnI5nAaILA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
