ansible_host: ENC[AES256_GCM,data:8eLty6vjbS4vEwo=,iv:BAVuj6eg01jCB7q/fdt54rOkT9S/WPC9qqrrJMRnurw=,tag:wB2kHfmxnUPSnAqMpSElWQ==,type:str]
ansible_user: ENC[AES256_GCM,data:zqXQfjE=,iv:DiiWoJcfJxjucUMlEsRnRNGVPlydUU/NEo5T3iy/NAU=,tag:rPA3jrDqbcBowo9ezhbeVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOUNMWWN2RjZ0REJVKzBo
            cU9pRXZCcUlFTjdnc2RuYk15aDk5L1dET2trCms0M0J1NHlIU1p1M1VWbFdMUEZ5
            ZWs2K2tHcHF0MXFtV3VFMUxxSURNKzQKLS0tIHQ3OFR0cUcyRVRMUEgyQytsRVNq
            S1NXRFF6cTdKOUJpY1l4Qkdla1NLWUEKDq/MP7rrde6U4vcrXd6BzDzLOPKQcYtW
            b2YFyqEMNdzplsA6OfHLiGThxCGLNCSSXS4vApMK2VSZAffYaLKztw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T12:05:07Z"
    mac: ENC[AES256_GCM,data:+p+gHIJGt0sTa8F5C7lcbUHp2Vvew5R7a5DysYjISuZJhF/EpaHbJYVnd79ZIj3p0TWdIQsz/gWIHeH2hrJCb1PWg3Y0wA1fyceeZAGlxO4Dkt2GDjVPVNKLTwAwJtSn+XARwGylLpdq7ZTbf991rbltL+1hlvDe3d+58sb+LM0=,iv:yjdwGUDtw4fTPP4lCzVkNWxRGpI8oI6HX/U0mLztSj0=,tag:3ZXkz1+Jd81PAl6j4FIpfQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
