ansible_host: ENC[AES256_GCM,data:H8Bk/C9TMe2kuEw=,iv:ezcoeAaRlJCPjt8F23n+0hwqNIBxCgZo5J1R2ZGRmKo=,tag:zGTHrlCX0+nPsvgY8Ns65g==,type:str]
ansible_user: ENC[AES256_GCM,data:jQ6AJTA=,iv:qQT/lt/RNM4XKntubolMp4+ae+ZPnfQc1UYrFRXulKo=,tag:HjWHNX5Z+ZooNG/Iv7i2EQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVLzVUTWJkRXFPOGJVampN
            WlhleFVwM0RyZWJRaDhrTExXU3pLdXVLMjE0ClhyM3F4bitqaWJvQzR2RGFoYk1k
            OHMvd0VmV01reFRyQ3V5azJGZGpTbHcKLS0tIGxOQ3NkSTFHdzNMRFJTdHZ5bmkr
            MUNFN296bFlxRlVReGZTZVBoOVBnemMKlgPP2M2fAgAnshBD9/TWEOzTU1hcpKjV
            Mlh1acRzeixBQtW8xqkVBhNBV+sA7uL1B5j1K73g0S4VTfOzlEEfFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
    lastmodified: "2026-08-23T15:59:07Z"
    mac: ENC[AES256_GCM,data:1O5JNBlS3BWLAs+GQtzVi+YhY2qUTBkkHCAVVZ6WeoXFsBEAxTJy9cnEQfibqvwLHV7UKk6JP++UDuRrS0l/iEtPHMra6qGeFQpS0saNV61k7VVu5aZ4w49jZoWZRNgh78E5VUtCn8l0BC+SHZIAzPWl7PMpkB/b0OrLq8GV/kw=,iv:gF4kroheXlgPWZPNxv5vX/7mhc7BCeqYpMkxo441iDY=,tag:Hv4CTfqcsQGP0Kx5fKKQRQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
