ansible_host: ENC[AES256_GCM,data:XMd5PPUHcwUbx1g=,iv:9e4eEPr655TPF4kM7tVMUUdA8chyqSCznfTKm15vFFA=,tag:8HLfab1rbn2+wf2Bewd3EA==,type:str]
ansible_user: ENC[AES256_GCM,data:jQ6AJTA=,iv:qQT/lt/RNM4XKntubolMp4+ae+ZPnfQc1UYrFRXulKo=,tag:HjWHNX5Z+ZooNG/Iv7i2EQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVLzVUTWJkRXFPOGJVampN
            WlhleFVwM0RyZWJRaDhrTExXU3pLdXVLMjE0ClhyM3F4bitqaWJvQzR2RGFoYk1k
            OHMvd0VmV01reFRyQ3V5azJGZGpTbHcKLS0tIGxOQ3NkSTFHdzNMRFJTdHZ5bmkr
            MUNFN296bFlxRlVReGZTZVBoOVBnemMKlgPP2M2fAgAnshBD9/TWEOzTU1hcpKjV
            Mlh1acRzeixBQtW8xqkVBhNBV+sA7uL1B5j1K73g0S4VTfOzlEEfFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
    lastmodified: "2026-08-24T13:48:42Z"
    mac: ENC[AES256_GCM,data:7OUSo83vH9M9fpGItF2BD9YCRtFIz/IUKdId23r6D3Bg8AQ5oyswxZVS8ytW6NX2Aej73J4qcGlPRVWnysQYxzOosemcUM3YuAYr6/lrmAMQXSmueKfMw0QQqqQf6PRpMmnxBOe03CR28evvLopq8chh0v8qDfOMg8MguxkHzIU=,iv:SJf4A649gXQBikxbji7YS3O1HKJ7zUPuSTc71NCZExk=,tag:9SJ0iVvaUGO9Tz25lVz4WA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
