x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: "3"

services:
  immich-postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich-postgres
    restart: always
    logging: *default-logging
    environment:
      - POSTGRES_PASSWORD=${IMMICH_PG_PASS:?IMMICH_PG_PASS is required}
      - POSTGRES_USER=${IMMICH_PG_USER:-}
      - POSTGRES_DB=${IMMICH_PG_DB:-}
      - POSTGRES_INITDB_ARGS=--data-checksums
      - TZ=${TZ:-}
    ports:
      - "${IMMICH_PG_PORT:-5433}:5432"
    volumes:
      - ${IMMICH_PG_PATH_DATA:?IMMICH_PG_PATH_DATA is required}:/var/lib/postgresql/data
    shm_size: 256mb
    networks:
      - db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${IMMICH_PG_USER:-} -d ${IMMICH_PG_DB:-}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 1GB
        reservations:
          memory: 512M

networks:
  db-net:
    external: true
