name: ran_permanent
filters:
  - Alert.GetScenario() startsWith "custom/ran-" && GetDecisionsCount(Alert.GetValue()) >= 5
decisions:
  - type: ban
    scope: Ip
    duration: 8760h
notifications:
  - file_alerts
on_success: break
---
name: ran_escalation
filters:
  - Alert.GetScenario() startsWith "custom/ran-"
decisions:
  - type: ban
    scope: Ip
    duration_expr: "Sprintf('%dh', 4 * (3 ^ GetDecisionsCount(Alert.GetValue())))"
notifications:
  - file_alerts
on_success: break
---
name: appsec_detection
filters:
  - Alert.GetScenario() contains "appsec"
notifications:
  - file_appsec
on_success: break
---
name: long_ban
filters:
  - Alert.Remediation == true && Alert.GetScope() == "Ip" && Alert.GetScenario() contains "geo-violation"
decisions:
  - type: ban
    duration: 24h
notifications:
  - file_alerts
on_success: break
---
name: default_ip_remediation
filters:
  - Alert.Remediation == true && Alert.GetScope() == "Ip"
decisions:
  - type: ban
    duration: 4h
notifications:
  - file_alerts
on_success: break
