# yaml-language-server: $schema=https://schemas.recyclarr.dev/v8/config-schema.json

radarr:
  radarr-german-uhd-alt:
    base_url: !env_var RADARR_API_URL
    api_key: !env_var RADARR_API_KEY

    quality_definition:
      type: movie

    quality_profiles:
      - trash_id: 425da1ba30711b55d2eb371437ec98d7  # [German] UHD Bluray + WEB (Alternative)
        reset_unmatched_scores:
          enabled: true

    custom_format_groups:
      add:
        - trash_id: ff204bbcecdd487d1cefcefdbf0c278d  # [Optional] Golden Rule UHD
        - trash_id: 0ca61b4b233178d07113082a7acff72d  # [Unwanted] Unwanted Formats German
      skip: []
