komodo_deploy_path: /docker/komodo
komodo_enabled: false
komodo_tz: Europe/Berlin
komodo_image_tag: "{{ komodo_version }}"
komodo_port: 9120
komodo_bind_ip: "127.0.0.1"
komodo_host: "https://komodo.local"
komodo_title: "Homelab"
komodo_first_server_name: "{{ inventory_hostname }}"
komodo_monitoring_interval: "15-sec"
komodo_resource_poll_interval: "5-min"
komodo_backups_path: /docker/komodo/backups
komodo_periphery_root: /docker/komodo/data
