ansible_host: ENC[AES256_GCM,data:udNIz7lFekY1+C9E/af+,iv:nhB6Lb77BVXkV6FFrDd877bjjGtMKvY+YSIP8flmC54=,tag:vVYzkJn/I7NGF+qfk1WLKw==,type:str]
ansible_user: ENC[AES256_GCM,data:gybzsik=,iv:46ezxwJZRl8mX7yV0i3Cd0pNfwX0mEXaLOgK+6bBN9c=,tag:YpjIwUmxBww8yd04wZ5+qw==,type:str]
hawser_dockhand_url: ENC[AES256_GCM,data:Xalux2z51u4YKldjyjOdGH4IcRtLKr+uxiZjc61vwpaLSVnYt/lMrQ==,iv:zCOnF6ScfK8o3bRpOj/6R/nKfgbG5RGVE8Z7hNphXQo=,tag:fWRwudfz59zoexfxOq1XPQ==,type:str]
hawser_dockhand_token: ENC[AES256_GCM,data:PM3tvDGZ3j2d0XyzmssuXqScBvC6lVGcDcVVYiYkUX5uuKXMcwcOsvbyFw==,iv:GB+EAd7fMZiTxcHuTXfzy6TrvjJZCgRFMwjXEwDoQ3g=,tag:zm4LLpcAmpZvwjH6LmkdjQ==,type:str]
#ENC[AES256_GCM,data:f1qm8JgLYtHiXhu+oYpUK6Q=,iv:ra0IH6tBxNidfzIMoyLvGo49qaQhGbQmoJqFd29FbPA=,tag:dYeNedXTDysIa6/QrhBEJQ==,type:comment]
bifrost_deploy_path: ENC[AES256_GCM,data:xY3CeLac310CoJyuXYmr,iv:vnRi/ly2sOB2abRJJiK+7HXoiKvusZbLROfnLN7IYo8=,tag:74CedKVb47uPS0yQtFBrxg==,type:str]
bifrost_peer_allowed_ips: ENC[AES256_GCM,data:RMCUpNhukwLzerSyRWls1ChkQ0ajBAIopLH3/bmyBCJph8LfIzH1EuXJNXbu,iv:FpM0w1/kghWAF+zpa13GpWWSWNnrHLZKjcSRJkDAuDw=,tag:bGoBY4YApa4zG4Qpgznsdw==,type:str]
bifrost_peer_keepalive: ENC[AES256_GCM,data:Xdc=,iv:GsSIhwzPmDf9OrNaPcLuXj8+W8wkjgotJ7d8zS+K51c=,tag:Tg/WObq/iddrD36cB8nleA==,type:int]
bifrost_peer_preshared_key: ENC[AES256_GCM,data:1+ft8Ef5ofpFXD9s+Q5egwTWZNnZ+swt3bK1dbEFfdnpkZA1SlGk3TxS63I=,iv:3pmmWwxq7gTevbkaqoylbvbGIzFr/fAo5tWm+htOtPA=,tag:FPuL6+48HbCCc3+ULaItOQ==,type:str]
bifrost_listen_port: ENC[AES256_GCM,data:HA==,iv:ug3b3zFSLTLqfxnjynpuvaw3bSJoeRuz/TFeDkalEJI=,tag:4IiuIPouw5XHp2ItoSYbtg==,type:int]
bifrost_mtu: ENC[AES256_GCM,data:7+PZEw==,iv:y/fJyoFet5is+/BzBcCFTORI//FVOOu+FPYBc8NkbZA=,tag:XdkfQZ4BT3cZfsx2e1c01w==,type:int]
bifrost_private_key: ENC[AES256_GCM,data:yWy5zi4nV51gR9PbcIDLA8fwureG8c96tS0oRBg3pI9PY7Q6pcGvMNV/wCc=,iv:OoZrX8xO/IR+ucHKKJTyvOYHYXuFy8QF9odLzR2FOoU=,tag:s2tz5B2SdnUW3wT3v7zvIA==,type:str]
bifrost_address: ENC[AES256_GCM,data:D9pdC9QuBXMLtwVs/YA=,iv:KWshVCgsdjOsgPC4nQqj0lxsBXUg8th9PZzU1XT223U=,tag:gOooamf7n6NmqDrMtFyBZw==,type:str]
bifrost_peer_public_key: ENC[AES256_GCM,data:gOgLTbRFfsHqMFD/fKjyqBAWSsX+YTfcDPBUao/rPhnyWK1wwUbnSoJJmPI=,iv:4SUPBjo2TQ/Y3Ntk86RjjsbyTypITTvpDYJJ2w75Osg=,tag:TQyb7Fo6aCU0kM/7WbPQOg==,type:str]
bifrost_peer_endpoint: ENC[AES256_GCM,data:3FTfVJeE4Q2hVx6XZxpz/OUwtNw0aHvQ9OqWaXcG7Swt,iv:p87lwCoH7r5JBemhqsaRnZ9JjpwgVLRcOJuXxiQPbSg=,tag:+YA4smYZRvMNLEvriOCnbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dFJHdXU1SmVJbDFlZ1c5
            SHNIWkV3NlpLVXl5aW16UWlHclFuKzkvVnhZCkhreDBTSW4xMC90TmNjWDF5enpq
            QWJIM21sVDVrZzFDY1F6NXkyb2ZSSHMKLS0tIE85ME5FR2xiV2QvanVEWDVSZit5
            dXQrdTU2TFVad3JDMzYybi9janBMTFUK4JcCoJEqGalUFvKb84Q3SXXvdkXblm+B
            vp57cwHhdo/F5+YW6g2dSqfh52rKhMJ3DqgkCLuSo22T6NLsrFuGsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T05:45:51Z"
    mac: ENC[AES256_GCM,data:hC7Zhf5NCQq3nwT30x9JO7Tr5fbg5+5XMKGJ9GKVFUfVd2S0Hm9K6XAPnEV+vDlipMuIM+TYd9lm/TZ6OKP3lpQWqr5kwzwQJ5nrGdElFATHLZ30lpsT+1Pm4jjjW3y2w6HPYr6gHLP7yT7oZ9UZFoTorr+ZjBLCscSg5Scp4bQ=,iv:RVIWrB5+KP4I+SR1M9tIgtSxV15L5XhQQigNgpVdxuE=,tag:o9IwpSkUP0zOU3fWx8pErA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
