agent_deploy_path: /docker/agent
agent_enabled: false
agent_bifrost: false
agent_tz: Europe/Berlin
agent_image_tag: "{{ komodo_version }}"
agent_connect_as: "{{ inventory_hostname }}"
agent_root_directory: /docker/agent/data
agent_include_disk_mounts: /etc/hostname
agent_disable_terminals: false
agent_disable_container_terminals: false
