version: 1
metadata:
  name: Session Settings
  labels:
    blueprints.goauthentik.io/instantiate: "true"

entries:
  # Override default authentication login stage with longer session
  - model: authentik_stages_user_login.userloginstage
    identifiers:
      name: default-authentication-login
    attrs:
      session_duration: hours=24
      remember_me_offset: days=30
      network_binding: no_binding
