ansible_host: ENC[AES256_GCM,data:oHxQ5aFy+xaa46E=,iv:ayKDP+dcgZ4kh8kRZdAfDkd8uNueLXxBT5z1WTcLzZo=,tag:/p5KQLE+Qb4kaH1lI5pytg==,type:str]
ansible_user: ENC[AES256_GCM,data:ltBisVc=,iv:w+8b30jHtf+/MuyVRqAEjNq8e/Cux5l9bc1eq6/sFng=,tag:2rLQJ06ECvuksYybfB/kdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWjQxVW5IS21ocUl4M1dQ
            ZllXbzI5dGl2M1pKWERZbnhTSmp5TjRaVkJzCmRpQUU2YjdMQzNnTzJMMlhxL1h5
            ZFRDeVQ0VGNWYm5xUFEyMDhQanlvU1UKLS0tIC93MVdic1BFaTBGRkR1ZUtZYmJB
            MzZHUXVTU1RGQS95L2htbk8yK0l4QzAKkoziDzEJsTzNIl48V5ujh8P9mIg+MMtZ
            wF4p15XFgGVFa0v3BAv1HLLHPM4ddYF9tcoRaHl4HbJJTpgctqcwnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-04T13:12:22Z"
    mac: ENC[AES256_GCM,data:dYZHg5RDkSOCJKZVAFh+HefQxnZODkbs7gBTcDYssp1UUSdDJ542Sinwv/zEk3mkY7t9aG3Dc1EBNwqIQCj7wfd9QPKsMiWsonv9Igpfleewe+cIE/XsaWSSC+njcMKTPjzlY32/PCXfBCm1hy9M/sWtkyvnSoOOY1DODjPyOXY=,iv:YWsN2xxjtklxwZnekeBP6tsxWb3h9N1zkJP662h6j0U=,tag:OoSuwz+AFNmyA3tiX8CQag==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
