ansible_host: ENC[AES256_GCM,data:oHxQ5aFy+xaa46E=,iv:ayKDP+dcgZ4kh8kRZdAfDkd8uNueLXxBT5z1WTcLzZo=,tag:/p5KQLE+Qb4kaH1lI5pytg==,type:str]
ansible_user: ENC[AES256_GCM,data:ltBisVc=,iv:w+8b30jHtf+/MuyVRqAEjNq8e/Cux5l9bc1eq6/sFng=,tag:2rLQJ06ECvuksYybfB/kdA==,type:str]
hawser_dockhand_url: ENC[AES256_GCM,data:dfyRgwao8EKLUc/56/8irb3WHcZIEVOUoJS/OZVzGx08yV3cUTA3uA==,iv:QCJ59Mv9L+3KTIRnDyizg6bDvHz4SRWjxcENZi4WHQM=,tag:nPT9jehsHCK/nw7nrIcGSw==,type:str]
hawser_dockhand_token: ENC[AES256_GCM,data:iNdW6NONH32TuxS34vpX9erhBu3KoB8WupICtUcwXVLnWIlBUXVGpBFDcQ==,iv:+k2s6Hi1T4tbYnTEp7xK88OETyLPIAiaYpuFUN4JCsM=,tag:5zDgnjNwISk+Q4ZrKjt2ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWjQxVW5IS21ocUl4M1dQ
            ZllXbzI5dGl2M1pKWERZbnhTSmp5TjRaVkJzCmRpQUU2YjdMQzNnTzJMMlhxL1h5
            ZFRDeVQ0VGNWYm5xUFEyMDhQanlvU1UKLS0tIC93MVdic1BFaTBGRkR1ZUtZYmJB
            MzZHUXVTU1RGQS95L2htbk8yK0l4QzAKkoziDzEJsTzNIl48V5ujh8P9mIg+MMtZ
            wF4p15XFgGVFa0v3BAv1HLLHPM4ddYF9tcoRaHl4HbJJTpgctqcwnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T16:48:46Z"
    mac: ENC[AES256_GCM,data:jqmoLljkLW5mTe6bLEBxYT9NjJEE+cZm4/eaYvnA607On1o0ewgs/wxEhIeMw1PWXRik+QBw+0ddWFgJHyOgvUmVZPttOyWnXaoRmPqjL7L3rKRoTNJ2VLwpMbhCFPRoRRQusMmXr4susVH0ru6h81SzFvDQpmAzaCZKVgGmz14=,iv:8zS8Bxg0aqrmh/KK4Cy1dRzfU7o5Bh4uf4Uc/EJ4YRo=,tag:3SpsxY1qi+euyGRiVjnwHg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
