x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: "3"

services:
  pihole:
    image: pihole/pihole:2026.07.2@sha256:f7d1be836e3bc608b56d82fc9904f5a831cdfbc0dc9c6d58f94e4c985c70038b
    platform: linux/arm/v6
    container_name: pihole
    restart: unless-stopped
    logging: *default-logging
    cap_add:
      - NET_ADMIN
    ports:
      - "${PIHOLE_PORT_DNS:?PIHOLE_PORT_DNS is required}:53/tcp"
      - "${PIHOLE_PORT_DNS:?PIHOLE_PORT_DNS is required}:53/udp"
      - "${PIHOLE_PORT_WEB:?PIHOLE_PORT_WEB is required}:80/tcp"
    environment:
      - TZ=${TZ:-}
      - FTLCONF_webserver_api_password=${PIHOLE_PASS:?PIHOLE_PASS is required}
      - FTLCONF_webserver_api_max_sessions=${PIHOLE_MAX_SESSIONS:-64}
    volumes:
      - ${PIHOLE_PATH_DATA:?PIHOLE_PATH_DATA is required}:/etc/pihole
      - ${PIHOLE_PATH_DNSMASQ:?PIHOLE_PATH_DNSMASQ is required}:/etc/dnsmasq.d
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 512M
        reservations:
          memory: 256M

  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:v0.11.2@sha256:951576b448c08df16cc6b46f90cc3b40c44e10dfb56e431dfd0f1ead7d435724
    platform: linux/arm/v6
    container_name: nebula-sync
    restart: unless-stopped
    logging: *default-logging
    environment:
      - PRIMARY=${NEBULA_PRIMARY:-}
      - REPLICAS=${NEBULA_REPLICAS:-}
      - FULL_SYNC=${NEBULA_FULL_SYNC:-}
      - RUN_GRAVITY=${NEBULA_RUN_GRAVITY:-}
      - CRON=${NEBULA_CRON:-}
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 128M
        reservations:
          memory: 64M
