apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: victoriametrics-metrics-datasource
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: false

  - name: VictoriaLogs
    uid: victorialogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victorialogs:9428
    editable: false
    jsonData:
      logLevelRules:
        - field: "level"
          value: "critical"
          level: "critical"
          operator: "equals"
          enabled: true
        - field: "level"
          value: "fatal"
          level: "critical"
          operator: "equals"
          enabled: true
        - field: "level"
          value: "error"
          level: "error"
          operator: "equals"
          enabled: true
        - field: "level"
          value: "warn"
          level: "warning"
          operator: "equals"
          enabled: true
        - field: "level"
          value: "warning"
          level: "warning"
          operator: "equals"
          enabled: true
        - field: "level"
          value: "info"
          level: "info"
          operator: "equals"
          enabled: true
        - field: "level"
          value: "debug"
          level: "debug"
          operator: "equals"
          enabled: true
        - field: "level"
          value: "trace"
          level: "trace"
          operator: "equals"
          enabled: true
