{
 "title": "Databases",
 "description": "PostgreSQL, MongoDB, and Redis health and performance.",
 "tags": [
  "database",
  "postgres",
  "mongodb",
  "redis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "📊 Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PostgreSQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"integrations/postgres\"}"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"integrations/mongodb\"}"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"integrations/redis\"}"
    }
   ]
  },
  {
   "title": "PG Total Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes{datname!~\"template.*\"})"
    }
   ]
  },
  {
   "title": "Mongo Total Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mongodb_dbstats_dataSize)" }
   ]
  },
  {
   "title": "Redis Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_memory_used_bytes" }
   ]
  },
  { "title": "🐘 PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Database Sizes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname!~\"template.*|postgres\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_fetched{datname!~\"template.*\"}[5m]))",
     "legendFormat": "fetched"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_returned{datname!~\"template.*\"}[5m]))",
     "legendFormat": "returned"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_inserted{datname!~\"template.*\"}[5m]))",
     "legendFormat": "inserted"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_updated{datname!~\"template.*\"}[5m]))",
     "legendFormat": "updated"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_deleted{datname!~\"template.*\"}[5m]))",
     "legendFormat": "deleted"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{datname!~\"template.*\"}) / (sum(pg_stat_database_blks_hit{datname!~\"template.*\"}) + sum(pg_stat_database_blks_read{datname!~\"template.*\"}))",
     "legendFormat": "cache hit ratio"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname!~\"template.*|postgres\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint[5m])",
     "legendFormat": "checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean[5m])",
     "legendFormat": "clean"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend[5m])",
     "legendFormat": "backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync[5m])",
     "legendFormat": "backend_fsync"
    }
   ]
  },
  {
   "title": "Conflicts / Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_deadlocks{datname!~\"template.*\"}[5m]))",
     "legendFormat": "deadlocks"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts{datname!~\"template.*\"}[5m]))",
     "legendFormat": "conflicts"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname!~\"template.*\"}[5m])) + sum(irate(pg_stat_database_xact_rollback{datname!~\"template.*\"}[5m]))"
    }
   ]
  },
  { "title": "🍃 MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Opcounters Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{type=\"insert\"}[5m])",
     "legendFormat": "insert"
    },
    {
     "expr": "rate(mongodb_op_counters_total{type=\"query\"}[5m])",
     "legendFormat": "query"
    },
    {
     "expr": "rate(mongodb_op_counters_total{type=\"update\"}[5m])",
     "legendFormat": "update"
    },
    {
     "expr": "rate(mongodb_op_counters_total{type=\"delete\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(mongodb_op_counters_total{type=\"getmore\"}[5m])",
     "legendFormat": "getmore"
    },
    {
     "expr": "rate(mongodb_op_counters_total{type=\"command\"}[5m])",
     "legendFormat": "command"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{state=\"inserted\"}[5m])",
     "legendFormat": "inserted"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{state=\"updated\"}[5m])",
     "legendFormat": "updated"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{state=\"deleted\"}[5m])",
     "legendFormat": "deleted"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{state=\"returned\"}[5m])",
     "legendFormat": "returned"
    }
   ]
  },
  {
   "title": "Read Latency (µs/op)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_latencies_latency_total{type=\"read\"}[5m]) / rate(mongodb_mongod_op_latencies_ops_total{type=\"read\"}[5m])",
     "legendFormat": "read latency"
    }
   ]
  },
  {
   "title": "Write Latency (µs/op)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_latencies_latency_total{type=\"write\"}[5m]) / rate(mongodb_mongod_op_latencies_ops_total{type=\"write\"}[5m])",
     "legendFormat": "write latency"
    }
   ]
  },
  {
   "title": "Command Latency (µs/op)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_latencies_latency_total{type=\"command\"}[5m]) / rate(mongodb_mongod_op_latencies_ops_total{type=\"command\"}[5m])",
     "legendFormat": "command latency"
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_connections{state=\"current\"}",
     "legendFormat": "current"
    },
    {
     "expr": "mongodb_connections{state=\"available\"}",
     "legendFormat": "available"
    },
    {
     "expr": "mongodb_connections{state=\"active\"}",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "WT Cache Used %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{type=\"total\"} / ignoring(type) mongodb_mongod_wiredtiger_cache_max_bytes * 100"
    }
   ]
  },
  {
   "title": "Storage per Database",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_dbstats_dataSize{database!~\"admin|config|local\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Cache Evictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_evicted_total{type=\"modified\"}[5m])",
     "legendFormat": "modified"
    },
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_evicted_total{type=\"unmodified\"}[5m])",
     "legendFormat": "unmodified"
    }
   ]
  },
  {
   "title": "🔴 Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used vs Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "redis_memory_used_bytes", "legendFormat": "used" },
      { "expr": "redis_memory_max_bytes", "legendFormat": "max" }
     ]
    },
    {
     "title": "Connected Clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "redis_connected_clients", "legendFormat": "clients" },
      { "expr": "redis_blocked_clients", "legendFormat": "blocked" }
     ]
    },
    {
     "title": "Commands / s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(redis_commands_processed_total[5m])",
       "legendFormat": "cmd/s"
      }
     ]
    },
    {
     "title": "Hit Rate %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(redis_keyspace_hits_total[5m]) / (rate(redis_keyspace_hits_total[5m]) + rate(redis_keyspace_misses_total[5m])) * 100",
       "legendFormat": "hit rate"
      }
     ]
    },
    {
     "title": "Evicted Keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(redis_evicted_keys_total[5m])",
       "legendFormat": "evicted"
      }
     ]
    },
    {
     "title": "Fragmentation Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "redis_mem_fragmentation_ratio", "legendFormat": "frag ratio" }
     ]
    },
    {
     "title": "Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(redis_net_input_bytes_total[5m])",
       "legendFormat": "in"
      },
      {
       "expr": "rate(redis_net_output_bytes_total[5m])",
       "legendFormat": "out"
      }
     ]
    }
   ]
  }
 ]
}